//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboutMe.Domain.Entity.Magazine
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MagazineEntities : DbContext
    {
        public MagazineEntities()
            : base("name=MagazineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Nullable<int>> SP_ADMIN_MAGAZINE_CNT(string uSE_YN, string sEARCH_COL, string sEARCH_KEYWORD)
        {
            var uSE_YNParameter = uSE_YN != null ?
                new ObjectParameter("USE_YN", uSE_YN) :
                new ObjectParameter("USE_YN", typeof(string));
    
            var sEARCH_COLParameter = sEARCH_COL != null ?
                new ObjectParameter("SEARCH_COL", sEARCH_COL) :
                new ObjectParameter("SEARCH_COL", typeof(string));
    
            var sEARCH_KEYWORDParameter = sEARCH_KEYWORD != null ?
                new ObjectParameter("SEARCH_KEYWORD", sEARCH_KEYWORD) :
                new ObjectParameter("SEARCH_KEYWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_ADMIN_MAGAZINE_CNT", uSE_YNParameter, sEARCH_COLParameter, sEARCH_KEYWORDParameter);
        }
    
        public virtual int SP_ADMIN_MAGAZINE_INS(string tITLE, string sUB_TITLE, string cONTENT_GBN, string tHUMB_IMG_PATH, string iMG_PATH, string mOVIE_URL, Nullable<int> dISPLAY_ORDER, string uSE_YN, string aDM_ID, ObjectParameter nEW_IDX)
        {
            var tITLEParameter = tITLE != null ?
                new ObjectParameter("TITLE", tITLE) :
                new ObjectParameter("TITLE", typeof(string));
    
            var sUB_TITLEParameter = sUB_TITLE != null ?
                new ObjectParameter("SUB_TITLE", sUB_TITLE) :
                new ObjectParameter("SUB_TITLE", typeof(string));
    
            var cONTENT_GBNParameter = cONTENT_GBN != null ?
                new ObjectParameter("CONTENT_GBN", cONTENT_GBN) :
                new ObjectParameter("CONTENT_GBN", typeof(string));
    
            var tHUMB_IMG_PATHParameter = tHUMB_IMG_PATH != null ?
                new ObjectParameter("THUMB_IMG_PATH", tHUMB_IMG_PATH) :
                new ObjectParameter("THUMB_IMG_PATH", typeof(string));
    
            var iMG_PATHParameter = iMG_PATH != null ?
                new ObjectParameter("IMG_PATH", iMG_PATH) :
                new ObjectParameter("IMG_PATH", typeof(string));
    
            var mOVIE_URLParameter = mOVIE_URL != null ?
                new ObjectParameter("MOVIE_URL", mOVIE_URL) :
                new ObjectParameter("MOVIE_URL", typeof(string));
    
            var dISPLAY_ORDERParameter = dISPLAY_ORDER.HasValue ?
                new ObjectParameter("DISPLAY_ORDER", dISPLAY_ORDER) :
                new ObjectParameter("DISPLAY_ORDER", typeof(int));
    
            var uSE_YNParameter = uSE_YN != null ?
                new ObjectParameter("USE_YN", uSE_YN) :
                new ObjectParameter("USE_YN", typeof(string));
    
            var aDM_IDParameter = aDM_ID != null ?
                new ObjectParameter("ADM_ID", aDM_ID) :
                new ObjectParameter("ADM_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ADMIN_MAGAZINE_INS", tITLEParameter, sUB_TITLEParameter, cONTENT_GBNParameter, tHUMB_IMG_PATHParameter, iMG_PATHParameter, mOVIE_URLParameter, dISPLAY_ORDERParameter, uSE_YNParameter, aDM_IDParameter, nEW_IDX);
        }
    
        public virtual ObjectResult<SP_ADMIN_MAGAZINE_SEL_Result> SP_ADMIN_MAGAZINE_SEL(string uSE_YN, string sEARCH_COL, string sEARCH_KEYWORD, Nullable<int> pAGE, Nullable<int> pAGESIZE)
        {
            var uSE_YNParameter = uSE_YN != null ?
                new ObjectParameter("USE_YN", uSE_YN) :
                new ObjectParameter("USE_YN", typeof(string));
    
            var sEARCH_COLParameter = sEARCH_COL != null ?
                new ObjectParameter("SEARCH_COL", sEARCH_COL) :
                new ObjectParameter("SEARCH_COL", typeof(string));
    
            var sEARCH_KEYWORDParameter = sEARCH_KEYWORD != null ?
                new ObjectParameter("SEARCH_KEYWORD", sEARCH_KEYWORD) :
                new ObjectParameter("SEARCH_KEYWORD", typeof(string));
    
            var pAGEParameter = pAGE.HasValue ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(int));
    
            var pAGESIZEParameter = pAGESIZE.HasValue ?
                new ObjectParameter("PAGESIZE", pAGESIZE) :
                new ObjectParameter("PAGESIZE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADMIN_MAGAZINE_SEL_Result>("SP_ADMIN_MAGAZINE_SEL", uSE_YNParameter, sEARCH_COLParameter, sEARCH_KEYWORDParameter, pAGEParameter, pAGESIZEParameter);
        }
    
        public virtual int SP_ADMIN_MAGAZINE_UPD(Nullable<int> iDX, string tITLE, string sUB_TITLE, string cONTENT_GBN, string tHUMB_IMG_PATH, string iMG_PATH, string mOVIE_URL, Nullable<int> dISPLAY_ORDER, string uSE_YN, string aDM_ID)
        {
            var iDXParameter = iDX.HasValue ?
                new ObjectParameter("IDX", iDX) :
                new ObjectParameter("IDX", typeof(int));
    
            var tITLEParameter = tITLE != null ?
                new ObjectParameter("TITLE", tITLE) :
                new ObjectParameter("TITLE", typeof(string));
    
            var sUB_TITLEParameter = sUB_TITLE != null ?
                new ObjectParameter("SUB_TITLE", sUB_TITLE) :
                new ObjectParameter("SUB_TITLE", typeof(string));
    
            var cONTENT_GBNParameter = cONTENT_GBN != null ?
                new ObjectParameter("CONTENT_GBN", cONTENT_GBN) :
                new ObjectParameter("CONTENT_GBN", typeof(string));
    
            var tHUMB_IMG_PATHParameter = tHUMB_IMG_PATH != null ?
                new ObjectParameter("THUMB_IMG_PATH", tHUMB_IMG_PATH) :
                new ObjectParameter("THUMB_IMG_PATH", typeof(string));
    
            var iMG_PATHParameter = iMG_PATH != null ?
                new ObjectParameter("IMG_PATH", iMG_PATH) :
                new ObjectParameter("IMG_PATH", typeof(string));
    
            var mOVIE_URLParameter = mOVIE_URL != null ?
                new ObjectParameter("MOVIE_URL", mOVIE_URL) :
                new ObjectParameter("MOVIE_URL", typeof(string));
    
            var dISPLAY_ORDERParameter = dISPLAY_ORDER.HasValue ?
                new ObjectParameter("DISPLAY_ORDER", dISPLAY_ORDER) :
                new ObjectParameter("DISPLAY_ORDER", typeof(int));
    
            var uSE_YNParameter = uSE_YN != null ?
                new ObjectParameter("USE_YN", uSE_YN) :
                new ObjectParameter("USE_YN", typeof(string));
    
            var aDM_IDParameter = aDM_ID != null ?
                new ObjectParameter("ADM_ID", aDM_ID) :
                new ObjectParameter("ADM_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ADMIN_MAGAZINE_UPD", iDXParameter, tITLEParameter, sUB_TITLEParameter, cONTENT_GBNParameter, tHUMB_IMG_PATHParameter, iMG_PATHParameter, mOVIE_URLParameter, dISPLAY_ORDERParameter, uSE_YNParameter, aDM_IDParameter);
        }
    
        public virtual ObjectResult<SP_ADMIN_MAGAZINE_VIEW_Result> SP_ADMIN_MAGAZINE_VIEW(Nullable<int> iDX)
        {
            var iDXParameter = iDX.HasValue ?
                new ObjectParameter("IDX", iDX) :
                new ObjectParameter("IDX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADMIN_MAGAZINE_VIEW_Result>("SP_ADMIN_MAGAZINE_VIEW", iDXParameter);
        }
    
        public virtual ObjectResult<SP_MAGAZINE_LIST_Result> SP_MAGAZINE_LIST()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MAGAZINE_LIST_Result>("SP_MAGAZINE_LIST");
        }
    
        public virtual ObjectResult<SP_MAGAZINE_VIEW_Result> SP_MAGAZINE_VIEW(Nullable<int> iDX)
        {
            var iDXParameter = iDX.HasValue ?
                new ObjectParameter("IDX", iDX) :
                new ObjectParameter("IDX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MAGAZINE_VIEW_Result>("SP_MAGAZINE_VIEW", iDXParameter);
        }
    }
}
