//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboutMe.Domain.Entity.AdminCoupon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_COUPON_KIND_CATEGORY
    {
        public int IDX { get; set; }
        public string CD_COUPON_KIND { get; set; }
        public string MEMO { get; set; }
        public string PLURAL_YN { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
    }
}
