//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboutMe.Domain.Entity.Qna
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QnaEntities : DbContext
    {
        public QnaEntities()
            : base("name=QnaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_QNA> TB_QNA { get; set; }
    
        public virtual ObjectResult<SP_TB_QNA_CNT_Result> SP_TB_QNA_CNT(string m_ID)
        {
            var m_IDParameter = m_ID != null ?
                new ObjectParameter("M_ID", m_ID) :
                new ObjectParameter("M_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_QNA_CNT_Result>("SP_TB_QNA_CNT", m_IDParameter);
        }
    
        public virtual ObjectResult<SP_TB_QNA_SEL_Result> SP_TB_QNA_SEL(string m_ID, Nullable<int> pAGE, Nullable<int> pAGESIZE)
        {
            var m_IDParameter = m_ID != null ?
                new ObjectParameter("M_ID", m_ID) :
                new ObjectParameter("M_ID", typeof(string));
    
            var pAGEParameter = pAGE.HasValue ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(int));
    
            var pAGESIZEParameter = pAGESIZE.HasValue ?
                new ObjectParameter("PAGESIZE", pAGESIZE) :
                new ObjectParameter("PAGESIZE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_QNA_SEL_Result>("SP_TB_QNA_SEL", m_IDParameter, pAGEParameter, pAGESIZEParameter);
        }
    
        public virtual int SP_TB_QNA_DEL(Nullable<int> iDX, ObjectParameter eRR_CODE)
        {
            var iDXParameter = iDX.HasValue ?
                new ObjectParameter("IDX", iDX) :
                new ObjectParameter("IDX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_QNA_DEL", iDXParameter, eRR_CODE);
        }
    
        public virtual ObjectResult<SP_TB_QNA_VIEW_Result> SP_TB_QNA_VIEW(Nullable<int> iDX)
        {
            var iDXParameter = iDX.HasValue ?
                new ObjectParameter("IDX", iDX) :
                new ObjectParameter("IDX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_QNA_VIEW_Result>("SP_TB_QNA_VIEW", iDXParameter);
        }
    
        public virtual int SP_TB_QNA_INS(string cATEGORY, string tITLE, string qUESTION, string sTATUS, string m_ID, ObjectParameter nEW_IDX)
        {
            var cATEGORYParameter = cATEGORY != null ?
                new ObjectParameter("CATEGORY", cATEGORY) :
                new ObjectParameter("CATEGORY", typeof(string));
    
            var tITLEParameter = tITLE != null ?
                new ObjectParameter("TITLE", tITLE) :
                new ObjectParameter("TITLE", typeof(string));
    
            var qUESTIONParameter = qUESTION != null ?
                new ObjectParameter("QUESTION", qUESTION) :
                new ObjectParameter("QUESTION", typeof(string));
    
            var sTATUSParameter = sTATUS != null ?
                new ObjectParameter("STATUS", sTATUS) :
                new ObjectParameter("STATUS", typeof(string));
    
            var m_IDParameter = m_ID != null ?
                new ObjectParameter("M_ID", m_ID) :
                new ObjectParameter("M_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_QNA_INS", cATEGORYParameter, tITLEParameter, qUESTIONParameter, sTATUSParameter, m_IDParameter, nEW_IDX);
        }
    
        public virtual int SP_TB_QNA_UPD(Nullable<int> iDX, string cATEGORY, string tITLE, string qUESTION, string m_ID, ObjectParameter eRR_CODE)
        {
            var iDXParameter = iDX.HasValue ?
                new ObjectParameter("IDX", iDX) :
                new ObjectParameter("IDX", typeof(int));
    
            var cATEGORYParameter = cATEGORY != null ?
                new ObjectParameter("CATEGORY", cATEGORY) :
                new ObjectParameter("CATEGORY", typeof(string));
    
            var tITLEParameter = tITLE != null ?
                new ObjectParameter("TITLE", tITLE) :
                new ObjectParameter("TITLE", typeof(string));
    
            var qUESTIONParameter = qUESTION != null ?
                new ObjectParameter("QUESTION", qUESTION) :
                new ObjectParameter("QUESTION", typeof(string));
    
            var m_IDParameter = m_ID != null ?
                new ObjectParameter("M_ID", m_ID) :
                new ObjectParameter("M_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_QNA_UPD", iDXParameter, cATEGORYParameter, tITLEParameter, qUESTIONParameter, m_IDParameter, eRR_CODE);
        }
    }
}
