//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboutMe.Domain.Entity.Cart
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CART
    {
        public int IDX { get; set; }
        public string M_ID { get; set; }
        public string SESSION_ID { get; set; }
        public string P_CODE { get; set; }
        public int P_COUNT { get; set; }
        public System.DateTime REG_DATE { get; set; }
    }
}
