//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboutMe.Domain.Entity.Notice
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_NOTICE
    {
        public int IDX { get; set; }
        public string TITLE { get; set; }
        public string CONTENTS { get; set; }
        public int VIEW_CNT { get; set; }
        public string DISPLAY_YN { get; set; }
        public string M_ID { get; set; }
        public System.DateTime REG_DATE { get; set; }
    }
}
