//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboutMe.Domain.Entity.AdminEtc
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN_MEMBER_DEPT
    {
        public int IDX { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
    }
}
