//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboutMe.Domain.Entity.AdminEtc
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ADMIN_MEMBER
    {
        public string ADM_ID { get; set; }
        public string ADM_NAME { get; set; }
        public string ADM_PWD { get; set; }
        public string ADM_GRADE { get; set; }
        public string ADM_EMAIL { get; set; }
        public string ADM_PHONE { get; set; }
        public Nullable<System.DateTime> ADM_INS_DATE { get; set; }
        public string ADM_USE_YN { get; set; }
    }
}
