//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboutMe.Domain.Entity.AdminPromotion
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PROMOTION_BY_TOTAL_MEM_GRADE
    {
        public int IDX { get; set; }
        public string CD_PROMOTION_TOTAL { get; set; }
        public string M_GBN { get; set; }
        public string M_GRADE { get; set; }
        public string USABLE_YN { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
    }
}
