//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboutMe.Domain.Entity.AdminPromotion
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PROMOTION_BY_TOTAL_CATEGORY
    {
        public int IDX { get; set; }
        public string PMO_TOTAL_CATEGORY { get; set; }
        public string PMO_TOTAL_CATEGORY_NAME { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
    }
}
