//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboutMe.Domain.Entity.Event
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EventEntities : DbContext
    {
        public EventEntities()
            : base("name=EventEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SP_ADMIN_EVENT_CNT_Result> SP_ADMIN_EVENT_CNT(string fROM_DATE, string tO_DATE, string iNG_GBN, string uSE_YN, string sEARCH_COL, string sEARCH_KEYWORD)
        {
            var fROM_DATEParameter = fROM_DATE != null ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(string));
    
            var tO_DATEParameter = tO_DATE != null ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(string));
    
            var iNG_GBNParameter = iNG_GBN != null ?
                new ObjectParameter("ING_GBN", iNG_GBN) :
                new ObjectParameter("ING_GBN", typeof(string));
    
            var uSE_YNParameter = uSE_YN != null ?
                new ObjectParameter("USE_YN", uSE_YN) :
                new ObjectParameter("USE_YN", typeof(string));
    
            var sEARCH_COLParameter = sEARCH_COL != null ?
                new ObjectParameter("SEARCH_COL", sEARCH_COL) :
                new ObjectParameter("SEARCH_COL", typeof(string));
    
            var sEARCH_KEYWORDParameter = sEARCH_KEYWORD != null ?
                new ObjectParameter("SEARCH_KEYWORD", sEARCH_KEYWORD) :
                new ObjectParameter("SEARCH_KEYWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADMIN_EVENT_CNT_Result>("SP_ADMIN_EVENT_CNT", fROM_DATEParameter, tO_DATEParameter, iNG_GBNParameter, uSE_YNParameter, sEARCH_COLParameter, sEARCH_KEYWORDParameter);
        }
    
        public virtual int SP_ADMIN_EVENT_INS(string eVENT_NAME, string fROM_DATE, string fROM_TIME, string tO_DATE, string tO_TIME, string eVENT_GBN, string wEB_CONTENTS, string mOBILE_FILE, string wEB_BANNER, string mOBILE_BANNER, string wEB_URL, string mOBILE_URL, string uSE_YN, string aDM_ID, ObjectParameter nEW_IDX)
        {
            var eVENT_NAMEParameter = eVENT_NAME != null ?
                new ObjectParameter("EVENT_NAME", eVENT_NAME) :
                new ObjectParameter("EVENT_NAME", typeof(string));
    
            var fROM_DATEParameter = fROM_DATE != null ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(string));
    
            var fROM_TIMEParameter = fROM_TIME != null ?
                new ObjectParameter("FROM_TIME", fROM_TIME) :
                new ObjectParameter("FROM_TIME", typeof(string));
    
            var tO_DATEParameter = tO_DATE != null ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(string));
    
            var tO_TIMEParameter = tO_TIME != null ?
                new ObjectParameter("TO_TIME", tO_TIME) :
                new ObjectParameter("TO_TIME", typeof(string));
    
            var eVENT_GBNParameter = eVENT_GBN != null ?
                new ObjectParameter("EVENT_GBN", eVENT_GBN) :
                new ObjectParameter("EVENT_GBN", typeof(string));
    
            var wEB_CONTENTSParameter = wEB_CONTENTS != null ?
                new ObjectParameter("WEB_CONTENTS", wEB_CONTENTS) :
                new ObjectParameter("WEB_CONTENTS", typeof(string));
    
            var mOBILE_FILEParameter = mOBILE_FILE != null ?
                new ObjectParameter("MOBILE_FILE", mOBILE_FILE) :
                new ObjectParameter("MOBILE_FILE", typeof(string));
    
            var wEB_BANNERParameter = wEB_BANNER != null ?
                new ObjectParameter("WEB_BANNER", wEB_BANNER) :
                new ObjectParameter("WEB_BANNER", typeof(string));
    
            var mOBILE_BANNERParameter = mOBILE_BANNER != null ?
                new ObjectParameter("MOBILE_BANNER", mOBILE_BANNER) :
                new ObjectParameter("MOBILE_BANNER", typeof(string));
    
            var wEB_URLParameter = wEB_URL != null ?
                new ObjectParameter("WEB_URL", wEB_URL) :
                new ObjectParameter("WEB_URL", typeof(string));
    
            var mOBILE_URLParameter = mOBILE_URL != null ?
                new ObjectParameter("MOBILE_URL", mOBILE_URL) :
                new ObjectParameter("MOBILE_URL", typeof(string));
    
            var uSE_YNParameter = uSE_YN != null ?
                new ObjectParameter("USE_YN", uSE_YN) :
                new ObjectParameter("USE_YN", typeof(string));
    
            var aDM_IDParameter = aDM_ID != null ?
                new ObjectParameter("ADM_ID", aDM_ID) :
                new ObjectParameter("ADM_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ADMIN_EVENT_INS", eVENT_NAMEParameter, fROM_DATEParameter, fROM_TIMEParameter, tO_DATEParameter, tO_TIMEParameter, eVENT_GBNParameter, wEB_CONTENTSParameter, mOBILE_FILEParameter, wEB_BANNERParameter, mOBILE_BANNERParameter, wEB_URLParameter, mOBILE_URLParameter, uSE_YNParameter, aDM_IDParameter, nEW_IDX);
        }
    
        public virtual int SP_ADMIN_EVENT_MAIN_DEL(string bANNER_GBN, string aDM_ID)
        {
            var bANNER_GBNParameter = bANNER_GBN != null ?
                new ObjectParameter("BANNER_GBN", bANNER_GBN) :
                new ObjectParameter("BANNER_GBN", typeof(string));
    
            var aDM_IDParameter = aDM_ID != null ?
                new ObjectParameter("ADM_ID", aDM_ID) :
                new ObjectParameter("ADM_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ADMIN_EVENT_MAIN_DEL", bANNER_GBNParameter, aDM_IDParameter);
        }
    
        public virtual int SP_ADMIN_EVENT_MAIN_UPD(string bANNER_GBN, string iMG, string uRL, string aDM_ID)
        {
            var bANNER_GBNParameter = bANNER_GBN != null ?
                new ObjectParameter("BANNER_GBN", bANNER_GBN) :
                new ObjectParameter("BANNER_GBN", typeof(string));
    
            var iMGParameter = iMG != null ?
                new ObjectParameter("IMG", iMG) :
                new ObjectParameter("IMG", typeof(string));
    
            var uRLParameter = uRL != null ?
                new ObjectParameter("URL", uRL) :
                new ObjectParameter("URL", typeof(string));
    
            var aDM_IDParameter = aDM_ID != null ?
                new ObjectParameter("ADM_ID", aDM_ID) :
                new ObjectParameter("ADM_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ADMIN_EVENT_MAIN_UPD", bANNER_GBNParameter, iMGParameter, uRLParameter, aDM_IDParameter);
        }
    
        public virtual ObjectResult<SP_ADMIN_EVENT_SEL_Result> SP_ADMIN_EVENT_SEL(string fROM_DATE, string tO_DATE, string iNG_GBN, string uSE_YN, string sEARCH_COL, string sEARCH_KEYWORD, Nullable<int> pAGE, Nullable<int> pAGESIZE)
        {
            var fROM_DATEParameter = fROM_DATE != null ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(string));
    
            var tO_DATEParameter = tO_DATE != null ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(string));
    
            var iNG_GBNParameter = iNG_GBN != null ?
                new ObjectParameter("ING_GBN", iNG_GBN) :
                new ObjectParameter("ING_GBN", typeof(string));
    
            var uSE_YNParameter = uSE_YN != null ?
                new ObjectParameter("USE_YN", uSE_YN) :
                new ObjectParameter("USE_YN", typeof(string));
    
            var sEARCH_COLParameter = sEARCH_COL != null ?
                new ObjectParameter("SEARCH_COL", sEARCH_COL) :
                new ObjectParameter("SEARCH_COL", typeof(string));
    
            var sEARCH_KEYWORDParameter = sEARCH_KEYWORD != null ?
                new ObjectParameter("SEARCH_KEYWORD", sEARCH_KEYWORD) :
                new ObjectParameter("SEARCH_KEYWORD", typeof(string));
    
            var pAGEParameter = pAGE.HasValue ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(int));
    
            var pAGESIZEParameter = pAGESIZE.HasValue ?
                new ObjectParameter("PAGESIZE", pAGESIZE) :
                new ObjectParameter("PAGESIZE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADMIN_EVENT_SEL_Result>("SP_ADMIN_EVENT_SEL", fROM_DATEParameter, tO_DATEParameter, iNG_GBNParameter, uSE_YNParameter, sEARCH_COLParameter, sEARCH_KEYWORDParameter, pAGEParameter, pAGESIZEParameter);
        }
    
        public virtual int SP_ADMIN_EVENT_UPD(Nullable<int> iDX, string eVENT_NAME, string fROM_DATE, string fROM_TIME, string tO_DATE, string tO_TIME, string eVENT_GBN, string wEB_CONTENTS, string mOBILE_FILE, string wEB_BANNER, string mOBILE_BANNER, string wEB_URL, string mOBILE_URL, string uSE_YN, string aDM_ID)
        {
            var iDXParameter = iDX.HasValue ?
                new ObjectParameter("IDX", iDX) :
                new ObjectParameter("IDX", typeof(int));
    
            var eVENT_NAMEParameter = eVENT_NAME != null ?
                new ObjectParameter("EVENT_NAME", eVENT_NAME) :
                new ObjectParameter("EVENT_NAME", typeof(string));
    
            var fROM_DATEParameter = fROM_DATE != null ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(string));
    
            var fROM_TIMEParameter = fROM_TIME != null ?
                new ObjectParameter("FROM_TIME", fROM_TIME) :
                new ObjectParameter("FROM_TIME", typeof(string));
    
            var tO_DATEParameter = tO_DATE != null ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(string));
    
            var tO_TIMEParameter = tO_TIME != null ?
                new ObjectParameter("TO_TIME", tO_TIME) :
                new ObjectParameter("TO_TIME", typeof(string));
    
            var eVENT_GBNParameter = eVENT_GBN != null ?
                new ObjectParameter("EVENT_GBN", eVENT_GBN) :
                new ObjectParameter("EVENT_GBN", typeof(string));
    
            var wEB_CONTENTSParameter = wEB_CONTENTS != null ?
                new ObjectParameter("WEB_CONTENTS", wEB_CONTENTS) :
                new ObjectParameter("WEB_CONTENTS", typeof(string));
    
            var mOBILE_FILEParameter = mOBILE_FILE != null ?
                new ObjectParameter("MOBILE_FILE", mOBILE_FILE) :
                new ObjectParameter("MOBILE_FILE", typeof(string));
    
            var wEB_BANNERParameter = wEB_BANNER != null ?
                new ObjectParameter("WEB_BANNER", wEB_BANNER) :
                new ObjectParameter("WEB_BANNER", typeof(string));
    
            var mOBILE_BANNERParameter = mOBILE_BANNER != null ?
                new ObjectParameter("MOBILE_BANNER", mOBILE_BANNER) :
                new ObjectParameter("MOBILE_BANNER", typeof(string));
    
            var wEB_URLParameter = wEB_URL != null ?
                new ObjectParameter("WEB_URL", wEB_URL) :
                new ObjectParameter("WEB_URL", typeof(string));
    
            var mOBILE_URLParameter = mOBILE_URL != null ?
                new ObjectParameter("MOBILE_URL", mOBILE_URL) :
                new ObjectParameter("MOBILE_URL", typeof(string));
    
            var uSE_YNParameter = uSE_YN != null ?
                new ObjectParameter("USE_YN", uSE_YN) :
                new ObjectParameter("USE_YN", typeof(string));
    
            var aDM_IDParameter = aDM_ID != null ?
                new ObjectParameter("ADM_ID", aDM_ID) :
                new ObjectParameter("ADM_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ADMIN_EVENT_UPD", iDXParameter, eVENT_NAMEParameter, fROM_DATEParameter, fROM_TIMEParameter, tO_DATEParameter, tO_TIMEParameter, eVENT_GBNParameter, wEB_CONTENTSParameter, mOBILE_FILEParameter, wEB_BANNERParameter, mOBILE_BANNERParameter, wEB_URLParameter, mOBILE_URLParameter, uSE_YNParameter, aDM_IDParameter);
        }
    
        public virtual ObjectResult<SP_ADMIN_EVENT_VIEW_Result> SP_ADMIN_EVENT_VIEW(Nullable<int> iDX)
        {
            var iDXParameter = iDX.HasValue ?
                new ObjectParameter("IDX", iDX) :
                new ObjectParameter("IDX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADMIN_EVENT_VIEW_Result>("SP_ADMIN_EVENT_VIEW", iDXParameter);
        }
    
        public virtual ObjectResult<SP_ADMIN_EVENT_MAIN_VIEW_Result> SP_ADMIN_EVENT_MAIN_VIEW()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADMIN_EVENT_MAIN_VIEW_Result>("SP_ADMIN_EVENT_MAIN_VIEW");
        }
    
        public virtual ObjectResult<SP_EVENT_END_LIST_Result> SP_EVENT_END_LIST(Nullable<int> pAGE, Nullable<int> pAGESIZE)
        {
            var pAGEParameter = pAGE.HasValue ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(int));
    
            var pAGESIZEParameter = pAGESIZE.HasValue ?
                new ObjectParameter("PAGESIZE", pAGESIZE) :
                new ObjectParameter("PAGESIZE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_EVENT_END_LIST_Result>("SP_EVENT_END_LIST", pAGEParameter, pAGESIZEParameter);
        }
    
        public virtual ObjectResult<SP_EVENT_ING_LIST_Result> SP_EVENT_ING_LIST(Nullable<int> pAGE, Nullable<int> pAGESIZE)
        {
            var pAGEParameter = pAGE.HasValue ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(int));
    
            var pAGESIZEParameter = pAGESIZE.HasValue ?
                new ObjectParameter("PAGESIZE", pAGESIZE) :
                new ObjectParameter("PAGESIZE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_EVENT_ING_LIST_Result>("SP_EVENT_ING_LIST", pAGEParameter, pAGESIZEParameter);
        }
    }
}
