//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboutMe.Domain.Entity.Faq
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FaqEntities : DbContext
    {
        public FaqEntities()
            : base("name=FaqEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_FAQ> TB_FAQ { get; set; }
    
        public virtual ObjectResult<SP_TB_FAQ_CNT_Result> SP_TB_FAQ_CNT(string sEARCH_COL, string sEARCH_KEYWORD, string dISPLAY_YN)
        {
            var sEARCH_COLParameter = sEARCH_COL != null ?
                new ObjectParameter("SEARCH_COL", sEARCH_COL) :
                new ObjectParameter("SEARCH_COL", typeof(string));
    
            var sEARCH_KEYWORDParameter = sEARCH_KEYWORD != null ?
                new ObjectParameter("SEARCH_KEYWORD", sEARCH_KEYWORD) :
                new ObjectParameter("SEARCH_KEYWORD", typeof(string));
    
            var dISPLAY_YNParameter = dISPLAY_YN != null ?
                new ObjectParameter("DISPLAY_YN", dISPLAY_YN) :
                new ObjectParameter("DISPLAY_YN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_FAQ_CNT_Result>("SP_TB_FAQ_CNT", sEARCH_COLParameter, sEARCH_KEYWORDParameter, dISPLAY_YNParameter);
        }
    
        public virtual int SP_TB_FAQ_DEL(Nullable<int> iDX, ObjectParameter eRR_CODE)
        {
            var iDXParameter = iDX.HasValue ?
                new ObjectParameter("IDX", iDX) :
                new ObjectParameter("IDX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_FAQ_DEL", iDXParameter, eRR_CODE);
        }
    
        public virtual int SP_TB_FAQ_INS(string cATEGORY, string tITLE, string qUESTION, string aNSWER, string dISPLAY_YN, string m_ID, ObjectParameter nEW_IDX)
        {
            var cATEGORYParameter = cATEGORY != null ?
                new ObjectParameter("CATEGORY", cATEGORY) :
                new ObjectParameter("CATEGORY", typeof(string));
    
            var tITLEParameter = tITLE != null ?
                new ObjectParameter("TITLE", tITLE) :
                new ObjectParameter("TITLE", typeof(string));
    
            var qUESTIONParameter = qUESTION != null ?
                new ObjectParameter("QUESTION", qUESTION) :
                new ObjectParameter("QUESTION", typeof(string));
    
            var aNSWERParameter = aNSWER != null ?
                new ObjectParameter("ANSWER", aNSWER) :
                new ObjectParameter("ANSWER", typeof(string));
    
            var dISPLAY_YNParameter = dISPLAY_YN != null ?
                new ObjectParameter("DISPLAY_YN", dISPLAY_YN) :
                new ObjectParameter("DISPLAY_YN", typeof(string));
    
            var m_IDParameter = m_ID != null ?
                new ObjectParameter("M_ID", m_ID) :
                new ObjectParameter("M_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_FAQ_INS", cATEGORYParameter, tITLEParameter, qUESTIONParameter, aNSWERParameter, dISPLAY_YNParameter, m_IDParameter, nEW_IDX);
        }
    
        public virtual ObjectResult<SP_TB_FAQ_SEL_Result> SP_TB_FAQ_SEL(string sEARCH_COL, string sEARCH_KEYWORD, string dISPLAY_YN, string sORT_COL, string sORT_DIR, Nullable<int> pAGE, Nullable<int> pAGESIZE)
        {
            var sEARCH_COLParameter = sEARCH_COL != null ?
                new ObjectParameter("SEARCH_COL", sEARCH_COL) :
                new ObjectParameter("SEARCH_COL", typeof(string));
    
            var sEARCH_KEYWORDParameter = sEARCH_KEYWORD != null ?
                new ObjectParameter("SEARCH_KEYWORD", sEARCH_KEYWORD) :
                new ObjectParameter("SEARCH_KEYWORD", typeof(string));
    
            var dISPLAY_YNParameter = dISPLAY_YN != null ?
                new ObjectParameter("DISPLAY_YN", dISPLAY_YN) :
                new ObjectParameter("DISPLAY_YN", typeof(string));
    
            var sORT_COLParameter = sORT_COL != null ?
                new ObjectParameter("SORT_COL", sORT_COL) :
                new ObjectParameter("SORT_COL", typeof(string));
    
            var sORT_DIRParameter = sORT_DIR != null ?
                new ObjectParameter("SORT_DIR", sORT_DIR) :
                new ObjectParameter("SORT_DIR", typeof(string));
    
            var pAGEParameter = pAGE.HasValue ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(int));
    
            var pAGESIZEParameter = pAGESIZE.HasValue ?
                new ObjectParameter("PAGESIZE", pAGESIZE) :
                new ObjectParameter("PAGESIZE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_FAQ_SEL_Result>("SP_TB_FAQ_SEL", sEARCH_COLParameter, sEARCH_KEYWORDParameter, dISPLAY_YNParameter, sORT_COLParameter, sORT_DIRParameter, pAGEParameter, pAGESIZEParameter);
        }
    
        public virtual int SP_TB_FAQ_UPD(Nullable<int> iDX, string cATEGORY, string tITLE, string qUESTION, string aNSWER, string dISPLAY_YN, string m_ID, ObjectParameter eRR_CODE)
        {
            var iDXParameter = iDX.HasValue ?
                new ObjectParameter("IDX", iDX) :
                new ObjectParameter("IDX", typeof(int));
    
            var cATEGORYParameter = cATEGORY != null ?
                new ObjectParameter("CATEGORY", cATEGORY) :
                new ObjectParameter("CATEGORY", typeof(string));
    
            var tITLEParameter = tITLE != null ?
                new ObjectParameter("TITLE", tITLE) :
                new ObjectParameter("TITLE", typeof(string));
    
            var qUESTIONParameter = qUESTION != null ?
                new ObjectParameter("QUESTION", qUESTION) :
                new ObjectParameter("QUESTION", typeof(string));
    
            var aNSWERParameter = aNSWER != null ?
                new ObjectParameter("ANSWER", aNSWER) :
                new ObjectParameter("ANSWER", typeof(string));
    
            var dISPLAY_YNParameter = dISPLAY_YN != null ?
                new ObjectParameter("DISPLAY_YN", dISPLAY_YN) :
                new ObjectParameter("DISPLAY_YN", typeof(string));
    
            var m_IDParameter = m_ID != null ?
                new ObjectParameter("M_ID", m_ID) :
                new ObjectParameter("M_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_FAQ_UPD", iDXParameter, cATEGORYParameter, tITLEParameter, qUESTIONParameter, aNSWERParameter, dISPLAY_YNParameter, m_IDParameter, eRR_CODE);
        }
    
        public virtual ObjectResult<SP_TB_FAQ_VIEW_Result> SP_TB_FAQ_VIEW(Nullable<int> iDX)
        {
            var iDXParameter = iDX.HasValue ?
                new ObjectParameter("IDX", iDX) :
                new ObjectParameter("IDX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_FAQ_VIEW_Result>("SP_TB_FAQ_VIEW", iDXParameter);
        }
    }
}
