//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboutMe.Domain.Entity.AdminPoint
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AdminPointEntities : DbContext
    {
        public AdminPointEntities()
            : base("name=AdminPointEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int SP_ADMIN_POINT_SAVE(string m_ID, Nullable<int> aMOUNT, string aDDITION_REASON, Nullable<int> oRDER_IDX, Nullable<int> rEVIEW_IDX, ObjectParameter rET_NUM, ObjectParameter rET_MESSAGE)
        {
            var m_IDParameter = m_ID != null ?
                new ObjectParameter("M_ID", m_ID) :
                new ObjectParameter("M_ID", typeof(string));
    
            var aMOUNTParameter = aMOUNT.HasValue ?
                new ObjectParameter("AMOUNT", aMOUNT) :
                new ObjectParameter("AMOUNT", typeof(int));
    
            var aDDITION_REASONParameter = aDDITION_REASON != null ?
                new ObjectParameter("ADDITION_REASON", aDDITION_REASON) :
                new ObjectParameter("ADDITION_REASON", typeof(string));
    
            var oRDER_IDXParameter = oRDER_IDX.HasValue ?
                new ObjectParameter("ORDER_IDX", oRDER_IDX) :
                new ObjectParameter("ORDER_IDX", typeof(int));
    
            var rEVIEW_IDXParameter = rEVIEW_IDX.HasValue ?
                new ObjectParameter("REVIEW_IDX", rEVIEW_IDX) :
                new ObjectParameter("REVIEW_IDX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ADMIN_POINT_SAVE", m_IDParameter, aMOUNTParameter, aDDITION_REASONParameter, oRDER_IDXParameter, rEVIEW_IDXParameter, rET_NUM, rET_MESSAGE);
        }
    
        public virtual int SP_ADMIN_POINT_USE(string m_ID, Nullable<int> uSE_POINT, string aDDITION_REASON, Nullable<int> oRDER_IDX, ObjectParameter rET_NUM, ObjectParameter rET_MESSAGE)
        {
            var m_IDParameter = m_ID != null ?
                new ObjectParameter("M_ID", m_ID) :
                new ObjectParameter("M_ID", typeof(string));
    
            var uSE_POINTParameter = uSE_POINT.HasValue ?
                new ObjectParameter("USE_POINT", uSE_POINT) :
                new ObjectParameter("USE_POINT", typeof(int));
    
            var aDDITION_REASONParameter = aDDITION_REASON != null ?
                new ObjectParameter("ADDITION_REASON", aDDITION_REASON) :
                new ObjectParameter("ADDITION_REASON", typeof(string));
    
            var oRDER_IDXParameter = oRDER_IDX.HasValue ?
                new ObjectParameter("ORDER_IDX", oRDER_IDX) :
                new ObjectParameter("ORDER_IDX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ADMIN_POINT_USE", m_IDParameter, uSE_POINTParameter, aDDITION_REASONParameter, oRDER_IDXParameter, rET_NUM, rET_MESSAGE);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_POINT_MEMBER_CNT(string sEARCH_KEY, string sEARCH_VALUE)
        {
            var sEARCH_KEYParameter = sEARCH_KEY != null ?
                new ObjectParameter("SEARCH_KEY", sEARCH_KEY) :
                new ObjectParameter("SEARCH_KEY", typeof(string));
    
            var sEARCH_VALUEParameter = sEARCH_VALUE != null ?
                new ObjectParameter("SEARCH_VALUE", sEARCH_VALUE) :
                new ObjectParameter("SEARCH_VALUE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_POINT_MEMBER_CNT", sEARCH_KEYParameter, sEARCH_VALUEParameter);
        }
    
        public virtual ObjectResult<SP_POINT_MEMBER_SEL_Result> SP_POINT_MEMBER_SEL(Nullable<int> pAGE, Nullable<int> pAGESIZE, string sEARCH_KEY, string sEARCH_VALUE)
        {
            var pAGEParameter = pAGE.HasValue ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(int));
    
            var pAGESIZEParameter = pAGESIZE.HasValue ?
                new ObjectParameter("PAGESIZE", pAGESIZE) :
                new ObjectParameter("PAGESIZE", typeof(int));
    
            var sEARCH_KEYParameter = sEARCH_KEY != null ?
                new ObjectParameter("SEARCH_KEY", sEARCH_KEY) :
                new ObjectParameter("SEARCH_KEY", typeof(string));
    
            var sEARCH_VALUEParameter = sEARCH_VALUE != null ?
                new ObjectParameter("SEARCH_VALUE", sEARCH_VALUE) :
                new ObjectParameter("SEARCH_VALUE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_POINT_MEMBER_SEL_Result>("SP_POINT_MEMBER_SEL", pAGEParameter, pAGESIZEParameter, sEARCH_KEYParameter, sEARCH_VALUEParameter);
        }
    }
}
