//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboutMe.Domain.Entity.AdminOrder
{
    using System;
    
    public partial class SP_ADMIN_ORDER_LIST_Cnt
    {
        public int COUNT { get; set; }
    }
}
