//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboutMe.Domain.Entity.AdminOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ORDER_DETAIL
    {
        public int ORDER_DETAIL_IDX { get; set; }
        public int ORDER_IDX { get; set; }
        public string ORDER_CODE { get; set; }
        public string ORDER_DETAIL_STATUS { get; set; }
        public string DELIVERY_NUM { get; set; }
        public Nullable<System.DateTime> DELIVERY_DATE { get; set; }
        public string P_CODE { get; set; }
        public string P_CATE_CODE { get; set; }
        public string P_CATE_NAME { get; set; }
        public string C_CATE_CODE { get; set; }
        public string C_CATE_NAME { get; set; }
        public string L_CATE_CODE { get; set; }
        public string L_CATE_NAME { get; set; }
        public string P_NAME { get; set; }
        public string P_IMG1_S { get; set; }
        public Nullable<int> PROMOTION_ID { get; set; }
        public int SELLING_PRICE { get; set; }
        public Nullable<int> DISCOUNT_RATE { get; set; }
        public Nullable<int> DISCOUNT_PRICE { get; set; }
        public Nullable<int> COUPON_CODE { get; set; }
        public Nullable<int> COUPON_DISCOUNT { get; set; }
        public Nullable<int> GRADE_DISCOUNT_PRICE { get; set; }
        public Nullable<int> EMP_DISCOUNT_PRICE { get; set; }
        public int USE_POINT { get; set; }
        public int POINT_ACCML { get; set; }
        public Nullable<System.DateTime> POINT_ACCML_DATE { get; set; }
        public int P_COUNT { get; set; }
        public Nullable<int> REAL_PAY_PRICE { get; set; }
        public System.DateTime REG_DATE { get; set; }
        public System.DateTime ORDER_DETAIL_STATUS_DATE { get; set; }
        public string EXCHANGE_YN { get; set; }
        public Nullable<System.DateTime> EXCHANGE_DATE { get; set; }
        public int EXCHANGE_COUNT { get; set; }
    }
}
