//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboutMe.Domain.Entity.AdminOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ORDER_LOG
    {
        public int IDX { get; set; }
        public int ORDER_IDX { get; set; }
        public string ORDER_CODE { get; set; }
        public string PROCESS_MEMO { get; set; }
        public string REG_ID { get; set; }
        public System.DateTime REG_DATE { get; set; }
    }
}
