//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboutMe.Domain.Entity.Recallbbs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RecallbbsEntities : DbContext
    {
        public RecallbbsEntities()
            : base("name=RecallbbsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_RECALL_BBS> TB_RECALL_BBS { get; set; }
    
        public virtual ObjectResult<SP_TB_RECALL_BBS_SEL_Result> SP_TB_RECALL_BBS_SEL(string sTART_DATE, string eND_DATE, string rEG_ID, string oRDER_CODE, Nullable<int> pAGE, Nullable<int> pAGESIZE)
        {
            var sTART_DATEParameter = sTART_DATE != null ?
                new ObjectParameter("START_DATE", sTART_DATE) :
                new ObjectParameter("START_DATE", typeof(string));
    
            var eND_DATEParameter = eND_DATE != null ?
                new ObjectParameter("END_DATE", eND_DATE) :
                new ObjectParameter("END_DATE", typeof(string));
    
            var rEG_IDParameter = rEG_ID != null ?
                new ObjectParameter("REG_ID", rEG_ID) :
                new ObjectParameter("REG_ID", typeof(string));
    
            var oRDER_CODEParameter = oRDER_CODE != null ?
                new ObjectParameter("ORDER_CODE", oRDER_CODE) :
                new ObjectParameter("ORDER_CODE", typeof(string));
    
            var pAGEParameter = pAGE.HasValue ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(int));
    
            var pAGESIZEParameter = pAGESIZE.HasValue ?
                new ObjectParameter("PAGESIZE", pAGESIZE) :
                new ObjectParameter("PAGESIZE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_RECALL_BBS_SEL_Result>("SP_TB_RECALL_BBS_SEL", sTART_DATEParameter, eND_DATEParameter, rEG_IDParameter, oRDER_CODEParameter, pAGEParameter, pAGESIZEParameter);
        }
    
        public virtual ObjectResult<SP_TB_RECALL_BBS_CNT_Result> SP_TB_RECALL_BBS_CNT(string sTART_DATE, string eND_DATE, string rEG_ID, string oRDER_CODE)
        {
            var sTART_DATEParameter = sTART_DATE != null ?
                new ObjectParameter("START_DATE", sTART_DATE) :
                new ObjectParameter("START_DATE", typeof(string));
    
            var eND_DATEParameter = eND_DATE != null ?
                new ObjectParameter("END_DATE", eND_DATE) :
                new ObjectParameter("END_DATE", typeof(string));
    
            var rEG_IDParameter = rEG_ID != null ?
                new ObjectParameter("REG_ID", rEG_ID) :
                new ObjectParameter("REG_ID", typeof(string));
    
            var oRDER_CODEParameter = oRDER_CODE != null ?
                new ObjectParameter("ORDER_CODE", oRDER_CODE) :
                new ObjectParameter("ORDER_CODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_RECALL_BBS_CNT_Result>("SP_TB_RECALL_BBS_CNT", sTART_DATEParameter, eND_DATEParameter, rEG_IDParameter, oRDER_CODEParameter);
        }
    
        public virtual ObjectResult<SP_TB_RECALL_BBS_VIEW_Result> SP_TB_RECALL_BBS_VIEW(Nullable<int> iDX, string rEG_ID, string oRDER_CODE)
        {
            var iDXParameter = iDX.HasValue ?
                new ObjectParameter("IDX", iDX) :
                new ObjectParameter("IDX", typeof(int));
    
            var rEG_IDParameter = rEG_ID != null ?
                new ObjectParameter("REG_ID", rEG_ID) :
                new ObjectParameter("REG_ID", typeof(string));
    
            var oRDER_CODEParameter = oRDER_CODE != null ?
                new ObjectParameter("ORDER_CODE", oRDER_CODE) :
                new ObjectParameter("ORDER_CODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_RECALL_BBS_VIEW_Result>("SP_TB_RECALL_BBS_VIEW", iDXParameter, rEG_IDParameter, oRDER_CODEParameter);
        }
    
        public virtual int SP_TB_RECALL_BBS_INS(string oRDER_CODE, Nullable<int> oRDER_DETAIL_IDX, Nullable<int> gUBUN, string tITLE, string cONTENTS, string rEG_ID)
        {
            var oRDER_CODEParameter = oRDER_CODE != null ?
                new ObjectParameter("ORDER_CODE", oRDER_CODE) :
                new ObjectParameter("ORDER_CODE", typeof(string));
    
            var oRDER_DETAIL_IDXParameter = oRDER_DETAIL_IDX.HasValue ?
                new ObjectParameter("ORDER_DETAIL_IDX", oRDER_DETAIL_IDX) :
                new ObjectParameter("ORDER_DETAIL_IDX", typeof(int));
    
            var gUBUNParameter = gUBUN.HasValue ?
                new ObjectParameter("GUBUN", gUBUN) :
                new ObjectParameter("GUBUN", typeof(int));
    
            var tITLEParameter = tITLE != null ?
                new ObjectParameter("TITLE", tITLE) :
                new ObjectParameter("TITLE", typeof(string));
    
            var cONTENTSParameter = cONTENTS != null ?
                new ObjectParameter("CONTENTS", cONTENTS) :
                new ObjectParameter("CONTENTS", typeof(string));
    
            var rEG_IDParameter = rEG_ID != null ?
                new ObjectParameter("REG_ID", rEG_ID) :
                new ObjectParameter("REG_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_RECALL_BBS_INS", oRDER_CODEParameter, oRDER_DETAIL_IDXParameter, gUBUNParameter, tITLEParameter, cONTENTSParameter, rEG_IDParameter);
        }
    
        public virtual int SP_TB_RECALL_BBS_UPD(Nullable<int> iDX, Nullable<int> gUBUN, string tITLE, string cONTENTS, string rEG_ID, string oRDER_CODE)
        {
            var iDXParameter = iDX.HasValue ?
                new ObjectParameter("IDX", iDX) :
                new ObjectParameter("IDX", typeof(int));
    
            var gUBUNParameter = gUBUN.HasValue ?
                new ObjectParameter("GUBUN", gUBUN) :
                new ObjectParameter("GUBUN", typeof(int));
    
            var tITLEParameter = tITLE != null ?
                new ObjectParameter("TITLE", tITLE) :
                new ObjectParameter("TITLE", typeof(string));
    
            var cONTENTSParameter = cONTENTS != null ?
                new ObjectParameter("CONTENTS", cONTENTS) :
                new ObjectParameter("CONTENTS", typeof(string));
    
            var rEG_IDParameter = rEG_ID != null ?
                new ObjectParameter("REG_ID", rEG_ID) :
                new ObjectParameter("REG_ID", typeof(string));
    
            var oRDER_CODEParameter = oRDER_CODE != null ?
                new ObjectParameter("ORDER_CODE", oRDER_CODE) :
                new ObjectParameter("ORDER_CODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_RECALL_BBS_UPD", iDXParameter, gUBUNParameter, tITLEParameter, cONTENTSParameter, rEG_IDParameter, oRDER_CODEParameter);
        }
    
        public virtual int SP_ADMIN_RECALL_ANSWER_UPD(Nullable<int> iDX, string aDM_ID, string cONFIRM_CONTENTS)
        {
            var iDXParameter = iDX.HasValue ?
                new ObjectParameter("IDX", iDX) :
                new ObjectParameter("IDX", typeof(int));
    
            var aDM_IDParameter = aDM_ID != null ?
                new ObjectParameter("ADM_ID", aDM_ID) :
                new ObjectParameter("ADM_ID", typeof(string));
    
            var cONFIRM_CONTENTSParameter = cONFIRM_CONTENTS != null ?
                new ObjectParameter("CONFIRM_CONTENTS", cONFIRM_CONTENTS) :
                new ObjectParameter("CONFIRM_CONTENTS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ADMIN_RECALL_ANSWER_UPD", iDXParameter, aDM_IDParameter, cONFIRM_CONTENTSParameter);
        }
    
        public virtual ObjectResult<SP_ADMIN_RECALL_BBS_CNT_Result> SP_ADMIN_RECALL_BBS_CNT(string sEARCH_COL, string sEARCH_KEYWORD, string sTATUS_YN)
        {
            var sEARCH_COLParameter = sEARCH_COL != null ?
                new ObjectParameter("SEARCH_COL", sEARCH_COL) :
                new ObjectParameter("SEARCH_COL", typeof(string));
    
            var sEARCH_KEYWORDParameter = sEARCH_KEYWORD != null ?
                new ObjectParameter("SEARCH_KEYWORD", sEARCH_KEYWORD) :
                new ObjectParameter("SEARCH_KEYWORD", typeof(string));
    
            var sTATUS_YNParameter = sTATUS_YN != null ?
                new ObjectParameter("STATUS_YN", sTATUS_YN) :
                new ObjectParameter("STATUS_YN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADMIN_RECALL_BBS_CNT_Result>("SP_ADMIN_RECALL_BBS_CNT", sEARCH_COLParameter, sEARCH_KEYWORDParameter, sTATUS_YNParameter);
        }
    
        public virtual ObjectResult<SP_ADMIN_RECALL_BBS_SEL_Result> SP_ADMIN_RECALL_BBS_SEL(string sEARCH_COL, string sEARCH_KEYWORD, string sTATUS_YN, string sORT_COL, string sORT_DIR, Nullable<int> pAGE, Nullable<int> pAGESIZE)
        {
            var sEARCH_COLParameter = sEARCH_COL != null ?
                new ObjectParameter("SEARCH_COL", sEARCH_COL) :
                new ObjectParameter("SEARCH_COL", typeof(string));
    
            var sEARCH_KEYWORDParameter = sEARCH_KEYWORD != null ?
                new ObjectParameter("SEARCH_KEYWORD", sEARCH_KEYWORD) :
                new ObjectParameter("SEARCH_KEYWORD", typeof(string));
    
            var sTATUS_YNParameter = sTATUS_YN != null ?
                new ObjectParameter("STATUS_YN", sTATUS_YN) :
                new ObjectParameter("STATUS_YN", typeof(string));
    
            var sORT_COLParameter = sORT_COL != null ?
                new ObjectParameter("SORT_COL", sORT_COL) :
                new ObjectParameter("SORT_COL", typeof(string));
    
            var sORT_DIRParameter = sORT_DIR != null ?
                new ObjectParameter("SORT_DIR", sORT_DIR) :
                new ObjectParameter("SORT_DIR", typeof(string));
    
            var pAGEParameter = pAGE.HasValue ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(int));
    
            var pAGESIZEParameter = pAGESIZE.HasValue ?
                new ObjectParameter("PAGESIZE", pAGESIZE) :
                new ObjectParameter("PAGESIZE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADMIN_RECALL_BBS_SEL_Result>("SP_ADMIN_RECALL_BBS_SEL", sEARCH_COLParameter, sEARCH_KEYWORDParameter, sTATUS_YNParameter, sORT_COLParameter, sORT_DIRParameter, pAGEParameter, pAGESIZEParameter);
        }
    
        public virtual ObjectResult<SP_ADMIN_RECALL_BBS_VIEW_Result> SP_ADMIN_RECALL_BBS_VIEW(Nullable<int> iDX)
        {
            var iDXParameter = iDX.HasValue ?
                new ObjectParameter("IDX", iDX) :
                new ObjectParameter("IDX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADMIN_RECALL_BBS_VIEW_Result>("SP_ADMIN_RECALL_BBS_VIEW", iDXParameter);
        }
    }
}
