//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboutMe.Domain.Entity.Recallbbs
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_RECALL_BBS
    {
        public int IDX { get; set; }
        public string ORDER_CODE { get; set; }
        public int ORDER_DETAIL_IDX { get; set; }
        public int GUBUN { get; set; }
        public string TITLE { get; set; }
        public string CONTENTS { get; set; }
        public string CONFIRM_CONTENTS { get; set; }
        public int STATUS { get; set; }
        public string ADM_ID { get; set; }
        public string REG_ID { get; set; }
        public System.DateTime REG_DATE { get; set; }
        public Nullable<System.DateTime> CONFIRM_DATE { get; set; }
    }
}
