//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboutMe.Domain.Entity.AdminFrontMember
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AdminFrontMemberEntities : DbContext
    {
        public AdminFrontMemberEntities()
            : base("name=AdminFrontMemberEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int SP_ADMIN_FRONT_MEMBER_PWD_UPD(string m_ID, string m_PWD, ObjectParameter eRR_CODE)
        {
            var m_IDParameter = m_ID != null ?
                new ObjectParameter("M_ID", m_ID) :
                new ObjectParameter("M_ID", typeof(string));
    
            var m_PWDParameter = m_PWD != null ?
                new ObjectParameter("M_PWD", m_PWD) :
                new ObjectParameter("M_PWD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ADMIN_FRONT_MEMBER_PWD_UPD", m_IDParameter, m_PWDParameter, eRR_CODE);
        }
    
        public virtual ObjectResult<SP_ADMIN_FRONT_MEMBER_VIEW_Result> SP_ADMIN_FRONT_MEMBER_SEL(string dATE_FROM, string dATE_TO, string gRADE_LIST, string gBN, string iS_RETIRE, string sEARCH_COL, string sEARCH_KEYWORD, string sORT_COL, string sORT_DIR, Nullable<int> pAGE, Nullable<int> pAGESIZE)
        {
            var dATE_FROMParameter = dATE_FROM != null ?
                new ObjectParameter("DATE_FROM", dATE_FROM) :
                new ObjectParameter("DATE_FROM", typeof(string));
    
            var dATE_TOParameter = dATE_TO != null ?
                new ObjectParameter("DATE_TO", dATE_TO) :
                new ObjectParameter("DATE_TO", typeof(string));
    
            var gRADE_LISTParameter = gRADE_LIST != null ?
                new ObjectParameter("GRADE_LIST", gRADE_LIST) :
                new ObjectParameter("GRADE_LIST", typeof(string));
    
            var gBNParameter = gBN != null ?
                new ObjectParameter("GBN", gBN) :
                new ObjectParameter("GBN", typeof(string));
    
            var iS_RETIREParameter = iS_RETIRE != null ?
                new ObjectParameter("IS_RETIRE", iS_RETIRE) :
                new ObjectParameter("IS_RETIRE", typeof(string));
    
            var sEARCH_COLParameter = sEARCH_COL != null ?
                new ObjectParameter("SEARCH_COL", sEARCH_COL) :
                new ObjectParameter("SEARCH_COL", typeof(string));
    
            var sEARCH_KEYWORDParameter = sEARCH_KEYWORD != null ?
                new ObjectParameter("SEARCH_KEYWORD", sEARCH_KEYWORD) :
                new ObjectParameter("SEARCH_KEYWORD", typeof(string));
    
            var sORT_COLParameter = sORT_COL != null ?
                new ObjectParameter("SORT_COL", sORT_COL) :
                new ObjectParameter("SORT_COL", typeof(string));
    
            var sORT_DIRParameter = sORT_DIR != null ?
                new ObjectParameter("SORT_DIR", sORT_DIR) :
                new ObjectParameter("SORT_DIR", typeof(string));
    
            var pAGEParameter = pAGE.HasValue ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(int));
    
            var pAGESIZEParameter = pAGESIZE.HasValue ?
                new ObjectParameter("PAGESIZE", pAGESIZE) :
                new ObjectParameter("PAGESIZE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADMIN_FRONT_MEMBER_VIEW_Result>("SP_ADMIN_FRONT_MEMBER_SEL", dATE_FROMParameter, dATE_TOParameter, gRADE_LISTParameter, gBNParameter, iS_RETIREParameter, sEARCH_COLParameter, sEARCH_KEYWORDParameter, sORT_COLParameter, sORT_DIRParameter, pAGEParameter, pAGESIZEParameter);
        }
    
        public virtual int SP_ADMIN_FRONT_MEMBER_UPD(string m_ID, string m_GRADE, string m_MOBILE, string m_PHONE, string m_EMAIL, string m_ZIPCODE, string m_ADDR1, string m_ADDR2, string m_ISSMS, string m_ISEMAIL, string m_ISDM, string m_SKIN_TROUBLE_CD, string m_GBN, string m_STAFF_COMAPNY, string m_STAFF_ID, string m_IS_RETIRE, string m_DEL_REASON, ObjectParameter eRR_CODE)
        {
            var m_IDParameter = m_ID != null ?
                new ObjectParameter("M_ID", m_ID) :
                new ObjectParameter("M_ID", typeof(string));
    
            var m_GRADEParameter = m_GRADE != null ?
                new ObjectParameter("M_GRADE", m_GRADE) :
                new ObjectParameter("M_GRADE", typeof(string));
    
            var m_MOBILEParameter = m_MOBILE != null ?
                new ObjectParameter("M_MOBILE", m_MOBILE) :
                new ObjectParameter("M_MOBILE", typeof(string));
    
            var m_PHONEParameter = m_PHONE != null ?
                new ObjectParameter("M_PHONE", m_PHONE) :
                new ObjectParameter("M_PHONE", typeof(string));
    
            var m_EMAILParameter = m_EMAIL != null ?
                new ObjectParameter("M_EMAIL", m_EMAIL) :
                new ObjectParameter("M_EMAIL", typeof(string));
    
            var m_ZIPCODEParameter = m_ZIPCODE != null ?
                new ObjectParameter("M_ZIPCODE", m_ZIPCODE) :
                new ObjectParameter("M_ZIPCODE", typeof(string));
    
            var m_ADDR1Parameter = m_ADDR1 != null ?
                new ObjectParameter("M_ADDR1", m_ADDR1) :
                new ObjectParameter("M_ADDR1", typeof(string));
    
            var m_ADDR2Parameter = m_ADDR2 != null ?
                new ObjectParameter("M_ADDR2", m_ADDR2) :
                new ObjectParameter("M_ADDR2", typeof(string));
    
            var m_ISSMSParameter = m_ISSMS != null ?
                new ObjectParameter("M_ISSMS", m_ISSMS) :
                new ObjectParameter("M_ISSMS", typeof(string));
    
            var m_ISEMAILParameter = m_ISEMAIL != null ?
                new ObjectParameter("M_ISEMAIL", m_ISEMAIL) :
                new ObjectParameter("M_ISEMAIL", typeof(string));
    
            var m_ISDMParameter = m_ISDM != null ?
                new ObjectParameter("M_ISDM", m_ISDM) :
                new ObjectParameter("M_ISDM", typeof(string));
    
            var m_SKIN_TROUBLE_CDParameter = m_SKIN_TROUBLE_CD != null ?
                new ObjectParameter("M_SKIN_TROUBLE_CD", m_SKIN_TROUBLE_CD) :
                new ObjectParameter("M_SKIN_TROUBLE_CD", typeof(string));
    
            var m_GBNParameter = m_GBN != null ?
                new ObjectParameter("M_GBN", m_GBN) :
                new ObjectParameter("M_GBN", typeof(string));
    
            var m_STAFF_COMAPNYParameter = m_STAFF_COMAPNY != null ?
                new ObjectParameter("M_STAFF_COMAPNY", m_STAFF_COMAPNY) :
                new ObjectParameter("M_STAFF_COMAPNY", typeof(string));
    
            var m_STAFF_IDParameter = m_STAFF_ID != null ?
                new ObjectParameter("M_STAFF_ID", m_STAFF_ID) :
                new ObjectParameter("M_STAFF_ID", typeof(string));
    
            var m_IS_RETIREParameter = m_IS_RETIRE != null ?
                new ObjectParameter("M_IS_RETIRE", m_IS_RETIRE) :
                new ObjectParameter("M_IS_RETIRE", typeof(string));
    
            var m_DEL_REASONParameter = m_DEL_REASON != null ?
                new ObjectParameter("M_DEL_REASON", m_DEL_REASON) :
                new ObjectParameter("M_DEL_REASON", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ADMIN_FRONT_MEMBER_UPD", m_IDParameter, m_GRADEParameter, m_MOBILEParameter, m_PHONEParameter, m_EMAILParameter, m_ZIPCODEParameter, m_ADDR1Parameter, m_ADDR2Parameter, m_ISSMSParameter, m_ISEMAILParameter, m_ISDMParameter, m_SKIN_TROUBLE_CDParameter, m_GBNParameter, m_STAFF_COMAPNYParameter, m_STAFF_IDParameter, m_IS_RETIREParameter, m_DEL_REASONParameter, eRR_CODE);
        }
    
        public virtual ObjectResult<SP_ADMIN_FRONT_MEMBER_VIEW_Result> SP_ADMIN_FRONT_MEMBER_VIEW(string m_ID)
        {
            var m_IDParameter = m_ID != null ?
                new ObjectParameter("M_ID", m_ID) :
                new ObjectParameter("M_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADMIN_FRONT_MEMBER_VIEW_Result>("SP_ADMIN_FRONT_MEMBER_VIEW", m_IDParameter);
        }
    
        public virtual ObjectResult<SP_ADMIN_FRONT_COMMON_CNT_Result> SP_ADMIN_FRONT_MEMBER_CNT(string dATE_FROM, string dATE_TO, string gRADE_LIST, string gBN, string iS_RETIRE, string sEARCH_COL, string sEARCH_KEYWORD)
        {
            var dATE_FROMParameter = dATE_FROM != null ?
                new ObjectParameter("DATE_FROM", dATE_FROM) :
                new ObjectParameter("DATE_FROM", typeof(string));
    
            var dATE_TOParameter = dATE_TO != null ?
                new ObjectParameter("DATE_TO", dATE_TO) :
                new ObjectParameter("DATE_TO", typeof(string));
    
            var gRADE_LISTParameter = gRADE_LIST != null ?
                new ObjectParameter("GRADE_LIST", gRADE_LIST) :
                new ObjectParameter("GRADE_LIST", typeof(string));
    
            var gBNParameter = gBN != null ?
                new ObjectParameter("GBN", gBN) :
                new ObjectParameter("GBN", typeof(string));
    
            var iS_RETIREParameter = iS_RETIRE != null ?
                new ObjectParameter("IS_RETIRE", iS_RETIRE) :
                new ObjectParameter("IS_RETIRE", typeof(string));
    
            var sEARCH_COLParameter = sEARCH_COL != null ?
                new ObjectParameter("SEARCH_COL", sEARCH_COL) :
                new ObjectParameter("SEARCH_COL", typeof(string));
    
            var sEARCH_KEYWORDParameter = sEARCH_KEYWORD != null ?
                new ObjectParameter("SEARCH_KEYWORD", sEARCH_KEYWORD) :
                new ObjectParameter("SEARCH_KEYWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADMIN_FRONT_COMMON_CNT_Result>("SP_ADMIN_FRONT_MEMBER_CNT", dATE_FROMParameter, dATE_TOParameter, gRADE_LISTParameter, gBNParameter, iS_RETIREParameter, sEARCH_COLParameter, sEARCH_KEYWORDParameter);
        }
    }
}
