//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboutMe.Domain.Entity.Member
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MemberEntities : DbContext
    {
        public MemberEntities()
            : base("name=MemberEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int SP_MEMBER_LOGIN_UPD(string m_ID)
        {
            var m_IDParameter = m_ID != null ?
                new ObjectParameter("M_ID", m_ID) :
                new ObjectParameter("M_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MEMBER_LOGIN_UPD", m_IDParameter);
        }
    
        public virtual ObjectResult<SP_MEMBER_VIEW_Result> SP_MEMBER_VIEW(string m_ID)
        {
            var m_IDParameter = m_ID != null ?
                new ObjectParameter("M_ID", m_ID) :
                new ObjectParameter("M_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MEMBER_VIEW_Result>("SP_MEMBER_VIEW", m_IDParameter);
        }
    
        public virtual int SP_MEMBER_DUP_CHK(string m_ID, ObjectParameter eRR_CODE)
        {
            var m_IDParameter = m_ID != null ?
                new ObjectParameter("M_ID", m_ID) :
                new ObjectParameter("M_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MEMBER_DUP_CHK", m_IDParameter, eRR_CODE);
        }
    
        public virtual int SP_MEMBER_FIND_ID(string m_NAME, string m_EMAIL, string m_MOBILE, ObjectParameter eRR_CODE, ObjectParameter rET_M_ID)
        {
            var m_NAMEParameter = m_NAME != null ?
                new ObjectParameter("M_NAME", m_NAME) :
                new ObjectParameter("M_NAME", typeof(string));
    
            var m_EMAILParameter = m_EMAIL != null ?
                new ObjectParameter("M_EMAIL", m_EMAIL) :
                new ObjectParameter("M_EMAIL", typeof(string));
    
            var m_MOBILEParameter = m_MOBILE != null ?
                new ObjectParameter("M_MOBILE", m_MOBILE) :
                new ObjectParameter("M_MOBILE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MEMBER_FIND_ID", m_NAMEParameter, m_EMAILParameter, m_MOBILEParameter, eRR_CODE, rET_M_ID);
        }
    
        public virtual int SP_MEMBER_FIND_PW(string m_ID, string m_NAME, string m_EMAIL, string m_MOBILE, string m_PWD_NEW, ObjectParameter eRR_CODE)
        {
            var m_IDParameter = m_ID != null ?
                new ObjectParameter("M_ID", m_ID) :
                new ObjectParameter("M_ID", typeof(string));
    
            var m_NAMEParameter = m_NAME != null ?
                new ObjectParameter("M_NAME", m_NAME) :
                new ObjectParameter("M_NAME", typeof(string));
    
            var m_EMAILParameter = m_EMAIL != null ?
                new ObjectParameter("M_EMAIL", m_EMAIL) :
                new ObjectParameter("M_EMAIL", typeof(string));
    
            var m_MOBILEParameter = m_MOBILE != null ?
                new ObjectParameter("M_MOBILE", m_MOBILE) :
                new ObjectParameter("M_MOBILE", typeof(string));
    
            var m_PWD_NEWParameter = m_PWD_NEW != null ?
                new ObjectParameter("M_PWD_NEW", m_PWD_NEW) :
                new ObjectParameter("M_PWD_NEW", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MEMBER_FIND_PW", m_IDParameter, m_NAMEParameter, m_EMAILParameter, m_MOBILEParameter, m_PWD_NEWParameter, eRR_CODE);
        }
    
        public virtual int SP_MEMBER_INS(string m_ID, string m_NAME, string m_PWD, string m_GRADE, string m_SEX, string m_BIRTHDAY, string m_MOBILE, string m_PHONE, string m_EMAIL, string m_ZIPCODE, string m_ADDR1, string m_ADDR2, string m_ISSMS, string m_ISEMAIL, string m_ISDM, string m_JOIN_MODE, string m_DI, string m_AGREE, string m_AGREE2, string m_SKIN_TROUBLE_CD, string m_GBN, string m_STAFF_COMPANY, string m_STAFF_ID, ObjectParameter eRR_CODE)
        {
            var m_IDParameter = m_ID != null ?
                new ObjectParameter("M_ID", m_ID) :
                new ObjectParameter("M_ID", typeof(string));
    
            var m_NAMEParameter = m_NAME != null ?
                new ObjectParameter("M_NAME", m_NAME) :
                new ObjectParameter("M_NAME", typeof(string));
    
            var m_PWDParameter = m_PWD != null ?
                new ObjectParameter("M_PWD", m_PWD) :
                new ObjectParameter("M_PWD", typeof(string));
    
            var m_GRADEParameter = m_GRADE != null ?
                new ObjectParameter("M_GRADE", m_GRADE) :
                new ObjectParameter("M_GRADE", typeof(string));
    
            var m_SEXParameter = m_SEX != null ?
                new ObjectParameter("M_SEX", m_SEX) :
                new ObjectParameter("M_SEX", typeof(string));
    
            var m_BIRTHDAYParameter = m_BIRTHDAY != null ?
                new ObjectParameter("M_BIRTHDAY", m_BIRTHDAY) :
                new ObjectParameter("M_BIRTHDAY", typeof(string));
    
            var m_MOBILEParameter = m_MOBILE != null ?
                new ObjectParameter("M_MOBILE", m_MOBILE) :
                new ObjectParameter("M_MOBILE", typeof(string));
    
            var m_PHONEParameter = m_PHONE != null ?
                new ObjectParameter("M_PHONE", m_PHONE) :
                new ObjectParameter("M_PHONE", typeof(string));
    
            var m_EMAILParameter = m_EMAIL != null ?
                new ObjectParameter("M_EMAIL", m_EMAIL) :
                new ObjectParameter("M_EMAIL", typeof(string));
    
            var m_ZIPCODEParameter = m_ZIPCODE != null ?
                new ObjectParameter("M_ZIPCODE", m_ZIPCODE) :
                new ObjectParameter("M_ZIPCODE", typeof(string));
    
            var m_ADDR1Parameter = m_ADDR1 != null ?
                new ObjectParameter("M_ADDR1", m_ADDR1) :
                new ObjectParameter("M_ADDR1", typeof(string));
    
            var m_ADDR2Parameter = m_ADDR2 != null ?
                new ObjectParameter("M_ADDR2", m_ADDR2) :
                new ObjectParameter("M_ADDR2", typeof(string));
    
            var m_ISSMSParameter = m_ISSMS != null ?
                new ObjectParameter("M_ISSMS", m_ISSMS) :
                new ObjectParameter("M_ISSMS", typeof(string));
    
            var m_ISEMAILParameter = m_ISEMAIL != null ?
                new ObjectParameter("M_ISEMAIL", m_ISEMAIL) :
                new ObjectParameter("M_ISEMAIL", typeof(string));
    
            var m_ISDMParameter = m_ISDM != null ?
                new ObjectParameter("M_ISDM", m_ISDM) :
                new ObjectParameter("M_ISDM", typeof(string));
    
            var m_JOIN_MODEParameter = m_JOIN_MODE != null ?
                new ObjectParameter("M_JOIN_MODE", m_JOIN_MODE) :
                new ObjectParameter("M_JOIN_MODE", typeof(string));
    
            var m_DIParameter = m_DI != null ?
                new ObjectParameter("M_DI", m_DI) :
                new ObjectParameter("M_DI", typeof(string));
    
            var m_AGREEParameter = m_AGREE != null ?
                new ObjectParameter("M_AGREE", m_AGREE) :
                new ObjectParameter("M_AGREE", typeof(string));
    
            var m_AGREE2Parameter = m_AGREE2 != null ?
                new ObjectParameter("M_AGREE2", m_AGREE2) :
                new ObjectParameter("M_AGREE2", typeof(string));
    
            var m_SKIN_TROUBLE_CDParameter = m_SKIN_TROUBLE_CD != null ?
                new ObjectParameter("M_SKIN_TROUBLE_CD", m_SKIN_TROUBLE_CD) :
                new ObjectParameter("M_SKIN_TROUBLE_CD", typeof(string));
    
            var m_GBNParameter = m_GBN != null ?
                new ObjectParameter("M_GBN", m_GBN) :
                new ObjectParameter("M_GBN", typeof(string));
    
            var m_STAFF_COMPANYParameter = m_STAFF_COMPANY != null ?
                new ObjectParameter("M_STAFF_COMPANY", m_STAFF_COMPANY) :
                new ObjectParameter("M_STAFF_COMPANY", typeof(string));
    
            var m_STAFF_IDParameter = m_STAFF_ID != null ?
                new ObjectParameter("M_STAFF_ID", m_STAFF_ID) :
                new ObjectParameter("M_STAFF_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MEMBER_INS", m_IDParameter, m_NAMEParameter, m_PWDParameter, m_GRADEParameter, m_SEXParameter, m_BIRTHDAYParameter, m_MOBILEParameter, m_PHONEParameter, m_EMAILParameter, m_ZIPCODEParameter, m_ADDR1Parameter, m_ADDR2Parameter, m_ISSMSParameter, m_ISEMAILParameter, m_ISDMParameter, m_JOIN_MODEParameter, m_DIParameter, m_AGREEParameter, m_AGREE2Parameter, m_SKIN_TROUBLE_CDParameter, m_GBNParameter, m_STAFF_COMPANYParameter, m_STAFF_IDParameter, eRR_CODE);
        }
    
        public virtual int SP_MEMBER_UPD(string m_ID, string m_MOBILE, string m_PHONE, string m_EMAIL, string m_ZIPCODE, string m_ADDR1, string m_ADDR2, string m_ISSMS, string m_ISEMAIL, string m_ISDM, ObjectParameter eRR_CODE)
        {
            var m_IDParameter = m_ID != null ?
                new ObjectParameter("M_ID", m_ID) :
                new ObjectParameter("M_ID", typeof(string));
    
            var m_MOBILEParameter = m_MOBILE != null ?
                new ObjectParameter("M_MOBILE", m_MOBILE) :
                new ObjectParameter("M_MOBILE", typeof(string));
    
            var m_PHONEParameter = m_PHONE != null ?
                new ObjectParameter("M_PHONE", m_PHONE) :
                new ObjectParameter("M_PHONE", typeof(string));
    
            var m_EMAILParameter = m_EMAIL != null ?
                new ObjectParameter("M_EMAIL", m_EMAIL) :
                new ObjectParameter("M_EMAIL", typeof(string));
    
            var m_ZIPCODEParameter = m_ZIPCODE != null ?
                new ObjectParameter("M_ZIPCODE", m_ZIPCODE) :
                new ObjectParameter("M_ZIPCODE", typeof(string));
    
            var m_ADDR1Parameter = m_ADDR1 != null ?
                new ObjectParameter("M_ADDR1", m_ADDR1) :
                new ObjectParameter("M_ADDR1", typeof(string));
    
            var m_ADDR2Parameter = m_ADDR2 != null ?
                new ObjectParameter("M_ADDR2", m_ADDR2) :
                new ObjectParameter("M_ADDR2", typeof(string));
    
            var m_ISSMSParameter = m_ISSMS != null ?
                new ObjectParameter("M_ISSMS", m_ISSMS) :
                new ObjectParameter("M_ISSMS", typeof(string));
    
            var m_ISEMAILParameter = m_ISEMAIL != null ?
                new ObjectParameter("M_ISEMAIL", m_ISEMAIL) :
                new ObjectParameter("M_ISEMAIL", typeof(string));
    
            var m_ISDMParameter = m_ISDM != null ?
                new ObjectParameter("M_ISDM", m_ISDM) :
                new ObjectParameter("M_ISDM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MEMBER_UPD", m_IDParameter, m_MOBILEParameter, m_PHONEParameter, m_EMAILParameter, m_ZIPCODEParameter, m_ADDR1Parameter, m_ADDR2Parameter, m_ISSMSParameter, m_ISEMAILParameter, m_ISDMParameter, eRR_CODE);
        }
    
        public virtual int SP_MEMBER_UPD_PWD(string m_ID, string m_PWD_OLD, string m_PWD_NEW, ObjectParameter eRR_CODE)
        {
            var m_IDParameter = m_ID != null ?
                new ObjectParameter("M_ID", m_ID) :
                new ObjectParameter("M_ID", typeof(string));
    
            var m_PWD_OLDParameter = m_PWD_OLD != null ?
                new ObjectParameter("M_PWD_OLD", m_PWD_OLD) :
                new ObjectParameter("M_PWD_OLD", typeof(string));
    
            var m_PWD_NEWParameter = m_PWD_NEW != null ?
                new ObjectParameter("M_PWD_NEW", m_PWD_NEW) :
                new ObjectParameter("M_PWD_NEW", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MEMBER_UPD_PWD", m_IDParameter, m_PWD_OLDParameter, m_PWD_NEWParameter, eRR_CODE);
        }
    
        public virtual int SP_MEMBER_UPD_RETIRE(string m_ID, string m_IS_RETIRE, string m_DEL_REASON, ObjectParameter eRR_CODE)
        {
            var m_IDParameter = m_ID != null ?
                new ObjectParameter("M_ID", m_ID) :
                new ObjectParameter("M_ID", typeof(string));
    
            var m_IS_RETIREParameter = m_IS_RETIRE != null ?
                new ObjectParameter("M_IS_RETIRE", m_IS_RETIRE) :
                new ObjectParameter("M_IS_RETIRE", typeof(string));
    
            var m_DEL_REASONParameter = m_DEL_REASON != null ?
                new ObjectParameter("M_DEL_REASON", m_DEL_REASON) :
                new ObjectParameter("M_DEL_REASON", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MEMBER_UPD_RETIRE", m_IDParameter, m_IS_RETIREParameter, m_DEL_REASONParameter, eRR_CODE);
        }
    
        public virtual int SP_MEMBER_UPD_SKIN_TROUBLE(string m_ID, string m_SKIN_TROUBLE_CD, ObjectParameter eRR_CODE)
        {
            var m_IDParameter = m_ID != null ?
                new ObjectParameter("M_ID", m_ID) :
                new ObjectParameter("M_ID", typeof(string));
    
            var m_SKIN_TROUBLE_CDParameter = m_SKIN_TROUBLE_CD != null ?
                new ObjectParameter("M_SKIN_TROUBLE_CD", m_SKIN_TROUBLE_CD) :
                new ObjectParameter("M_SKIN_TROUBLE_CD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MEMBER_UPD_SKIN_TROUBLE", m_IDParameter, m_SKIN_TROUBLE_CDParameter, eRR_CODE);
        }
    
        public virtual int SP_MEMBER_REALNAME_LOG_INS(string wORK_TMP_ID, string m_JOIN_TYPE, string rESULT_CODE, string tRAN_NO, string m_NAME, string di, string ci, string m_BIRTHDAY, string m_SEX, string nation, string rETURN_MSG_ALL, string iP)
        {
            var wORK_TMP_IDParameter = wORK_TMP_ID != null ?
                new ObjectParameter("WORK_TMP_ID", wORK_TMP_ID) :
                new ObjectParameter("WORK_TMP_ID", typeof(string));
    
            var m_JOIN_TYPEParameter = m_JOIN_TYPE != null ?
                new ObjectParameter("M_JOIN_TYPE", m_JOIN_TYPE) :
                new ObjectParameter("M_JOIN_TYPE", typeof(string));
    
            var rESULT_CODEParameter = rESULT_CODE != null ?
                new ObjectParameter("RESULT_CODE", rESULT_CODE) :
                new ObjectParameter("RESULT_CODE", typeof(string));
    
            var tRAN_NOParameter = tRAN_NO != null ?
                new ObjectParameter("TRAN_NO", tRAN_NO) :
                new ObjectParameter("TRAN_NO", typeof(string));
    
            var m_NAMEParameter = m_NAME != null ?
                new ObjectParameter("M_NAME", m_NAME) :
                new ObjectParameter("M_NAME", typeof(string));
    
            var diParameter = di != null ?
                new ObjectParameter("di", di) :
                new ObjectParameter("di", typeof(string));
    
            var ciParameter = ci != null ?
                new ObjectParameter("ci", ci) :
                new ObjectParameter("ci", typeof(string));
    
            var m_BIRTHDAYParameter = m_BIRTHDAY != null ?
                new ObjectParameter("M_BIRTHDAY", m_BIRTHDAY) :
                new ObjectParameter("M_BIRTHDAY", typeof(string));
    
            var m_SEXParameter = m_SEX != null ?
                new ObjectParameter("M_SEX", m_SEX) :
                new ObjectParameter("M_SEX", typeof(string));
    
            var nationParameter = nation != null ?
                new ObjectParameter("nation", nation) :
                new ObjectParameter("nation", typeof(string));
    
            var rETURN_MSG_ALLParameter = rETURN_MSG_ALL != null ?
                new ObjectParameter("RETURN_MSG_ALL", rETURN_MSG_ALL) :
                new ObjectParameter("RETURN_MSG_ALL", typeof(string));
    
            var iPParameter = iP != null ?
                new ObjectParameter("IP", iP) :
                new ObjectParameter("IP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MEMBER_REALNAME_LOG_INS", wORK_TMP_IDParameter, m_JOIN_TYPEParameter, rESULT_CODEParameter, tRAN_NOParameter, m_NAMEParameter, diParameter, ciParameter, m_BIRTHDAYParameter, m_SEXParameter, nationParameter, rETURN_MSG_ALLParameter, iPParameter);
        }
    
        public virtual ObjectResult<SP_MEMBER_REALNAME_LOG_VIEW_Result> SP_MEMBER_REALNAME_LOG_VIEW(string wORK_TMP_ID)
        {
            var wORK_TMP_IDParameter = wORK_TMP_ID != null ?
                new ObjectParameter("WORK_TMP_ID", wORK_TMP_ID) :
                new ObjectParameter("WORK_TMP_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MEMBER_REALNAME_LOG_VIEW_Result>("SP_MEMBER_REALNAME_LOG_VIEW", wORK_TMP_IDParameter);
        }
    
        public virtual int SP_MEMBER_FIND_DI(string m_DI, ObjectParameter eRR_CODE, ObjectParameter rET_M_ID)
        {
            var m_DIParameter = m_DI != null ?
                new ObjectParameter("M_DI", m_DI) :
                new ObjectParameter("M_DI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MEMBER_FIND_DI", m_DIParameter, eRR_CODE, rET_M_ID);
        }
    }
}
