//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboutMe.Domain.Entity.Sample
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SampleEntities : DbContext
    {
        public SampleEntities()
            : base("name=SampleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Nullable<int>> SP_ADMIN_SAMPLE_CNT(string fROM_DATE, string tO_DATE, string iNG_GBN, string uSE_YN, string sEARCH_COL, string sEARCH_KEYWORD)
        {
            var fROM_DATEParameter = fROM_DATE != null ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(string));
    
            var tO_DATEParameter = tO_DATE != null ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(string));
    
            var iNG_GBNParameter = iNG_GBN != null ?
                new ObjectParameter("ING_GBN", iNG_GBN) :
                new ObjectParameter("ING_GBN", typeof(string));
    
            var uSE_YNParameter = uSE_YN != null ?
                new ObjectParameter("USE_YN", uSE_YN) :
                new ObjectParameter("USE_YN", typeof(string));
    
            var sEARCH_COLParameter = sEARCH_COL != null ?
                new ObjectParameter("SEARCH_COL", sEARCH_COL) :
                new ObjectParameter("SEARCH_COL", typeof(string));
    
            var sEARCH_KEYWORDParameter = sEARCH_KEYWORD != null ?
                new ObjectParameter("SEARCH_KEYWORD", sEARCH_KEYWORD) :
                new ObjectParameter("SEARCH_KEYWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_ADMIN_SAMPLE_CNT", fROM_DATEParameter, tO_DATEParameter, iNG_GBNParameter, uSE_YNParameter, sEARCH_COLParameter, sEARCH_KEYWORDParameter);
        }
    
        public virtual int SP_ADMIN_SAMPLE_INS(string sAMPLE_NAME, string fROM_DATE, string fROM_TIME, string tO_DATE, string tO_TIME, string sAMPLE_GBN, string wEB_CONTENTS, string mOBILE_FILE, string wEB_BANNER, string mOBILE_BANNER, string uSE_YN, string aDM_ID, ObjectParameter nEW_IDX)
        {
            var sAMPLE_NAMEParameter = sAMPLE_NAME != null ?
                new ObjectParameter("SAMPLE_NAME", sAMPLE_NAME) :
                new ObjectParameter("SAMPLE_NAME", typeof(string));
    
            var fROM_DATEParameter = fROM_DATE != null ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(string));
    
            var fROM_TIMEParameter = fROM_TIME != null ?
                new ObjectParameter("FROM_TIME", fROM_TIME) :
                new ObjectParameter("FROM_TIME", typeof(string));
    
            var tO_DATEParameter = tO_DATE != null ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(string));
    
            var tO_TIMEParameter = tO_TIME != null ?
                new ObjectParameter("TO_TIME", tO_TIME) :
                new ObjectParameter("TO_TIME", typeof(string));
    
            var sAMPLE_GBNParameter = sAMPLE_GBN != null ?
                new ObjectParameter("SAMPLE_GBN", sAMPLE_GBN) :
                new ObjectParameter("SAMPLE_GBN", typeof(string));
    
            var wEB_CONTENTSParameter = wEB_CONTENTS != null ?
                new ObjectParameter("WEB_CONTENTS", wEB_CONTENTS) :
                new ObjectParameter("WEB_CONTENTS", typeof(string));
    
            var mOBILE_FILEParameter = mOBILE_FILE != null ?
                new ObjectParameter("MOBILE_FILE", mOBILE_FILE) :
                new ObjectParameter("MOBILE_FILE", typeof(string));
    
            var wEB_BANNERParameter = wEB_BANNER != null ?
                new ObjectParameter("WEB_BANNER", wEB_BANNER) :
                new ObjectParameter("WEB_BANNER", typeof(string));
    
            var mOBILE_BANNERParameter = mOBILE_BANNER != null ?
                new ObjectParameter("MOBILE_BANNER", mOBILE_BANNER) :
                new ObjectParameter("MOBILE_BANNER", typeof(string));
    
            var uSE_YNParameter = uSE_YN != null ?
                new ObjectParameter("USE_YN", uSE_YN) :
                new ObjectParameter("USE_YN", typeof(string));
    
            var aDM_IDParameter = aDM_ID != null ?
                new ObjectParameter("ADM_ID", aDM_ID) :
                new ObjectParameter("ADM_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ADMIN_SAMPLE_INS", sAMPLE_NAMEParameter, fROM_DATEParameter, fROM_TIMEParameter, tO_DATEParameter, tO_TIMEParameter, sAMPLE_GBNParameter, wEB_CONTENTSParameter, mOBILE_FILEParameter, wEB_BANNERParameter, mOBILE_BANNERParameter, uSE_YNParameter, aDM_IDParameter, nEW_IDX);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_ADMIN_SAMPLE_MEMBER_CNT(Nullable<int> sAMPLE_IDX)
        {
            var sAMPLE_IDXParameter = sAMPLE_IDX.HasValue ?
                new ObjectParameter("SAMPLE_IDX", sAMPLE_IDX) :
                new ObjectParameter("SAMPLE_IDX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_ADMIN_SAMPLE_MEMBER_CNT", sAMPLE_IDXParameter);
        }
    
        public virtual ObjectResult<SP_ADMIN_SAMPLE_MEMBER_SEL_Result> SP_ADMIN_SAMPLE_MEMBER_SEL(Nullable<int> sAMPLE_IDX, Nullable<int> pAGE, Nullable<int> pAGESIZE)
        {
            var sAMPLE_IDXParameter = sAMPLE_IDX.HasValue ?
                new ObjectParameter("SAMPLE_IDX", sAMPLE_IDX) :
                new ObjectParameter("SAMPLE_IDX", typeof(int));
    
            var pAGEParameter = pAGE.HasValue ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(int));
    
            var pAGESIZEParameter = pAGESIZE.HasValue ?
                new ObjectParameter("PAGESIZE", pAGESIZE) :
                new ObjectParameter("PAGESIZE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADMIN_SAMPLE_MEMBER_SEL_Result>("SP_ADMIN_SAMPLE_MEMBER_SEL", sAMPLE_IDXParameter, pAGEParameter, pAGESIZEParameter);
        }
    
        public virtual ObjectResult<SP_ADMIN_SAMPLE_SEL_Result> SP_ADMIN_SAMPLE_SEL(string fROM_DATE, string tO_DATE, string iNG_GBN, string uSE_YN, string sEARCH_COL, string sEARCH_KEYWORD, Nullable<int> pAGE, Nullable<int> pAGESIZE)
        {
            var fROM_DATEParameter = fROM_DATE != null ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(string));
    
            var tO_DATEParameter = tO_DATE != null ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(string));
    
            var iNG_GBNParameter = iNG_GBN != null ?
                new ObjectParameter("ING_GBN", iNG_GBN) :
                new ObjectParameter("ING_GBN", typeof(string));
    
            var uSE_YNParameter = uSE_YN != null ?
                new ObjectParameter("USE_YN", uSE_YN) :
                new ObjectParameter("USE_YN", typeof(string));
    
            var sEARCH_COLParameter = sEARCH_COL != null ?
                new ObjectParameter("SEARCH_COL", sEARCH_COL) :
                new ObjectParameter("SEARCH_COL", typeof(string));
    
            var sEARCH_KEYWORDParameter = sEARCH_KEYWORD != null ?
                new ObjectParameter("SEARCH_KEYWORD", sEARCH_KEYWORD) :
                new ObjectParameter("SEARCH_KEYWORD", typeof(string));
    
            var pAGEParameter = pAGE.HasValue ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(int));
    
            var pAGESIZEParameter = pAGESIZE.HasValue ?
                new ObjectParameter("PAGESIZE", pAGESIZE) :
                new ObjectParameter("PAGESIZE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADMIN_SAMPLE_SEL_Result>("SP_ADMIN_SAMPLE_SEL", fROM_DATEParameter, tO_DATEParameter, iNG_GBNParameter, uSE_YNParameter, sEARCH_COLParameter, sEARCH_KEYWORDParameter, pAGEParameter, pAGESIZEParameter);
        }
    
        public virtual int SP_ADMIN_SAMPLE_UPD(Nullable<int> iDX, string sAMPLE_NAME, string fROM_DATE, string fROM_TIME, string tO_DATE, string tO_TIME, string sAMPLE_GBN, string wEB_CONTENTS, string mOBILE_FILE, string wEB_BANNER, string mOBILE_BANNER, string uSE_YN, string aDM_ID)
        {
            var iDXParameter = iDX.HasValue ?
                new ObjectParameter("IDX", iDX) :
                new ObjectParameter("IDX", typeof(int));
    
            var sAMPLE_NAMEParameter = sAMPLE_NAME != null ?
                new ObjectParameter("SAMPLE_NAME", sAMPLE_NAME) :
                new ObjectParameter("SAMPLE_NAME", typeof(string));
    
            var fROM_DATEParameter = fROM_DATE != null ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(string));
    
            var fROM_TIMEParameter = fROM_TIME != null ?
                new ObjectParameter("FROM_TIME", fROM_TIME) :
                new ObjectParameter("FROM_TIME", typeof(string));
    
            var tO_DATEParameter = tO_DATE != null ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(string));
    
            var tO_TIMEParameter = tO_TIME != null ?
                new ObjectParameter("TO_TIME", tO_TIME) :
                new ObjectParameter("TO_TIME", typeof(string));
    
            var sAMPLE_GBNParameter = sAMPLE_GBN != null ?
                new ObjectParameter("SAMPLE_GBN", sAMPLE_GBN) :
                new ObjectParameter("SAMPLE_GBN", typeof(string));
    
            var wEB_CONTENTSParameter = wEB_CONTENTS != null ?
                new ObjectParameter("WEB_CONTENTS", wEB_CONTENTS) :
                new ObjectParameter("WEB_CONTENTS", typeof(string));
    
            var mOBILE_FILEParameter = mOBILE_FILE != null ?
                new ObjectParameter("MOBILE_FILE", mOBILE_FILE) :
                new ObjectParameter("MOBILE_FILE", typeof(string));
    
            var wEB_BANNERParameter = wEB_BANNER != null ?
                new ObjectParameter("WEB_BANNER", wEB_BANNER) :
                new ObjectParameter("WEB_BANNER", typeof(string));
    
            var mOBILE_BANNERParameter = mOBILE_BANNER != null ?
                new ObjectParameter("MOBILE_BANNER", mOBILE_BANNER) :
                new ObjectParameter("MOBILE_BANNER", typeof(string));
    
            var uSE_YNParameter = uSE_YN != null ?
                new ObjectParameter("USE_YN", uSE_YN) :
                new ObjectParameter("USE_YN", typeof(string));
    
            var aDM_IDParameter = aDM_ID != null ?
                new ObjectParameter("ADM_ID", aDM_ID) :
                new ObjectParameter("ADM_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ADMIN_SAMPLE_UPD", iDXParameter, sAMPLE_NAMEParameter, fROM_DATEParameter, fROM_TIMEParameter, tO_DATEParameter, tO_TIMEParameter, sAMPLE_GBNParameter, wEB_CONTENTSParameter, mOBILE_FILEParameter, wEB_BANNERParameter, mOBILE_BANNERParameter, uSE_YNParameter, aDM_IDParameter);
        }
    
        public virtual ObjectResult<SP_ADMIN_SAMPLE_VIEW_Result> SP_ADMIN_SAMPLE_VIEW(Nullable<int> iDX)
        {
            var iDXParameter = iDX.HasValue ?
                new ObjectParameter("IDX", iDX) :
                new ObjectParameter("IDX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADMIN_SAMPLE_VIEW_Result>("SP_ADMIN_SAMPLE_VIEW", iDXParameter);
        }
    
        public virtual int SP_SAMPLE_REQUEST(Nullable<int> sAMPLE_IDX, string m_ID)
        {

            var sAMPLE_IDXParameter = sAMPLE_IDX.HasValue ?
                new ObjectParameter("SAMPLE_IDX", sAMPLE_IDX) :
                new ObjectParameter("SAMPLE_IDX", typeof(int));
    
            var m_IDParameter = m_ID != null ?
                new ObjectParameter("M_ID", m_ID) :
                new ObjectParameter("M_ID", typeof(string));
            
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SAMPLE_REQUEST", sAMPLE_IDXParameter, m_IDParameter);
            
        }
    
        public virtual ObjectResult<SP_SAMPLE_VIEW_Result> SP_SAMPLE_VIEW(Nullable<int> iDX)
        {
            var iDXParameter = iDX.HasValue ?
                new ObjectParameter("IDX", iDX) :
                new ObjectParameter("IDX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SAMPLE_VIEW_Result>("SP_SAMPLE_VIEW", iDXParameter);
        }
    }
}
