//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboutMe.Domain.Entity.OrderStat
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OrderStatEntities : DbContext
    {
        public OrderStatEntities()
            : base("name=OrderStatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SP_ADMIN_STAT_ORDER_CATEGORY_Result> SP_ADMIN_STAT_ORDER_CATEGORY(string fROM_DATE, string tO_DATE, Nullable<bool> pAT_GUBUN1, Nullable<bool> pAT_GUBUN2, Nullable<bool> mEMBER_GBN1, Nullable<bool> mEMBER_GBN2, Nullable<bool> mEMBER_GBN3, string cateCode)
        {
            var fROM_DATEParameter = fROM_DATE != null ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(string));
    
            var tO_DATEParameter = tO_DATE != null ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(string));
    
            var pAT_GUBUN1Parameter = pAT_GUBUN1.HasValue ?
                new ObjectParameter("PAT_GUBUN1", pAT_GUBUN1) :
                new ObjectParameter("PAT_GUBUN1", typeof(bool));
    
            var pAT_GUBUN2Parameter = pAT_GUBUN2.HasValue ?
                new ObjectParameter("PAT_GUBUN2", pAT_GUBUN2) :
                new ObjectParameter("PAT_GUBUN2", typeof(bool));
    
            var mEMBER_GBN1Parameter = mEMBER_GBN1.HasValue ?
                new ObjectParameter("MEMBER_GBN1", mEMBER_GBN1) :
                new ObjectParameter("MEMBER_GBN1", typeof(bool));
    
            var mEMBER_GBN2Parameter = mEMBER_GBN2.HasValue ?
                new ObjectParameter("MEMBER_GBN2", mEMBER_GBN2) :
                new ObjectParameter("MEMBER_GBN2", typeof(bool));
    
            var mEMBER_GBN3Parameter = mEMBER_GBN3.HasValue ?
                new ObjectParameter("MEMBER_GBN3", mEMBER_GBN3) :
                new ObjectParameter("MEMBER_GBN3", typeof(bool));
    
            var cateCodeParameter = cateCode != null ?
                new ObjectParameter("cateCode", cateCode) :
                new ObjectParameter("cateCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADMIN_STAT_ORDER_CATEGORY_Result>("SP_ADMIN_STAT_ORDER_CATEGORY", fROM_DATEParameter, tO_DATEParameter, pAT_GUBUN1Parameter, pAT_GUBUN2Parameter, mEMBER_GBN1Parameter, mEMBER_GBN2Parameter, mEMBER_GBN3Parameter, cateCodeParameter);
        }
    
        public virtual ObjectResult<SP_ADMIN_STAT_ORDER_DAY_Result> SP_ADMIN_STAT_ORDER_DAY(string fROM_DATE, string tO_DATE, Nullable<bool> pAT_GUBUN1, Nullable<bool> pAT_GUBUN2, Nullable<bool> mEMBER_GBN1, Nullable<bool> mEMBER_GBN2, Nullable<bool> mEMBER_GBN3)
        {
            var fROM_DATEParameter = fROM_DATE != null ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(string));
    
            var tO_DATEParameter = tO_DATE != null ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(string));
    
            var pAT_GUBUN1Parameter = pAT_GUBUN1.HasValue ?
                new ObjectParameter("PAT_GUBUN1", pAT_GUBUN1) :
                new ObjectParameter("PAT_GUBUN1", typeof(bool));
    
            var pAT_GUBUN2Parameter = pAT_GUBUN2.HasValue ?
                new ObjectParameter("PAT_GUBUN2", pAT_GUBUN2) :
                new ObjectParameter("PAT_GUBUN2", typeof(bool));
    
            var mEMBER_GBN1Parameter = mEMBER_GBN1.HasValue ?
                new ObjectParameter("MEMBER_GBN1", mEMBER_GBN1) :
                new ObjectParameter("MEMBER_GBN1", typeof(bool));
    
            var mEMBER_GBN2Parameter = mEMBER_GBN2.HasValue ?
                new ObjectParameter("MEMBER_GBN2", mEMBER_GBN2) :
                new ObjectParameter("MEMBER_GBN2", typeof(bool));
    
            var mEMBER_GBN3Parameter = mEMBER_GBN3.HasValue ?
                new ObjectParameter("MEMBER_GBN3", mEMBER_GBN3) :
                new ObjectParameter("MEMBER_GBN3", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADMIN_STAT_ORDER_DAY_Result>("SP_ADMIN_STAT_ORDER_DAY", fROM_DATEParameter, tO_DATEParameter, pAT_GUBUN1Parameter, pAT_GUBUN2Parameter, mEMBER_GBN1Parameter, mEMBER_GBN2Parameter, mEMBER_GBN3Parameter);
        }
    }
}
