//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboutMe.Domain.Entity.AdminProduct
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AdminProductEntities : DbContext
    {
        public AdminProductEntities()
            : base("name=AdminProductEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_CATEGORY> TB_CATEGORY { get; set; }
        public virtual DbSet<TB_PRODUCT_INFO> TB_PRODUCT_INFO { get; set; }
    
        public virtual ObjectResult<SP_ADMIN_CATEGORY_NAME_SEL_Result> SP_ADMIN_CATEGORY_NAME_SEL(string dEPTH1_CODE, string cATE_GBN, string lIST_GBN)
        {
            var dEPTH1_CODEParameter = dEPTH1_CODE != null ?
                new ObjectParameter("DEPTH1_CODE", dEPTH1_CODE) :
                new ObjectParameter("DEPTH1_CODE", typeof(string));
    
            var cATE_GBNParameter = cATE_GBN != null ?
                new ObjectParameter("CATE_GBN", cATE_GBN) :
                new ObjectParameter("CATE_GBN", typeof(string));
    
            var lIST_GBNParameter = lIST_GBN != null ?
                new ObjectParameter("LIST_GBN", lIST_GBN) :
                new ObjectParameter("LIST_GBN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADMIN_CATEGORY_NAME_SEL_Result>("SP_ADMIN_CATEGORY_NAME_SEL", dEPTH1_CODEParameter, cATE_GBNParameter, lIST_GBNParameter);
        }
    
        public virtual ObjectResult<SP_ADMIN_CATEGORY_ONE_SEL_Result> SP_ADMIN_CATEGORY_ONE_SEL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADMIN_CATEGORY_ONE_SEL_Result>("SP_ADMIN_CATEGORY_ONE_SEL");
        }
    
        public virtual int SP_ADMIN_CATEGORY_ONE_UPD(Nullable<int> iDX, string dEPTH1_NAME, string dISPLAY_YN, Nullable<int> rE_SORT, ObjectParameter iNTRESULT)
        {
            var iDXParameter = iDX.HasValue ?
                new ObjectParameter("IDX", iDX) :
                new ObjectParameter("IDX", typeof(int));
    
            var dEPTH1_NAMEParameter = dEPTH1_NAME != null ?
                new ObjectParameter("DEPTH1_NAME", dEPTH1_NAME) :
                new ObjectParameter("DEPTH1_NAME", typeof(string));
    
            var dISPLAY_YNParameter = dISPLAY_YN != null ?
                new ObjectParameter("DISPLAY_YN", dISPLAY_YN) :
                new ObjectParameter("DISPLAY_YN", typeof(string));
    
            var rE_SORTParameter = rE_SORT.HasValue ?
                new ObjectParameter("RE_SORT", rE_SORT) :
                new ObjectParameter("RE_SORT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ADMIN_CATEGORY_ONE_UPD", iDXParameter, dEPTH1_NAMEParameter, dISPLAY_YNParameter, rE_SORTParameter, iNTRESULT);
        }
    
        public virtual int SP_ADMIN_CATEGORY_TWO_INS(string cATE_GBN, string dEPTH1_CODE, string dEPTH2_NAME, ObjectParameter iNTRESULT)
        {
            var cATE_GBNParameter = cATE_GBN != null ?
                new ObjectParameter("CATE_GBN", cATE_GBN) :
                new ObjectParameter("CATE_GBN", typeof(string));
    
            var dEPTH1_CODEParameter = dEPTH1_CODE != null ?
                new ObjectParameter("DEPTH1_CODE", dEPTH1_CODE) :
                new ObjectParameter("DEPTH1_CODE", typeof(string));
    
            var dEPTH2_NAMEParameter = dEPTH2_NAME != null ?
                new ObjectParameter("DEPTH2_NAME", dEPTH2_NAME) :
                new ObjectParameter("DEPTH2_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ADMIN_CATEGORY_TWO_INS", cATE_GBNParameter, dEPTH1_CODEParameter, dEPTH2_NAMEParameter, iNTRESULT);
        }
    
        public virtual ObjectResult<SP_ADMIN_CATEGORY_TWO_SEL_Result> SP_ADMIN_CATEGORY_TWO_SEL(string cATE_GBN, string dEPTH1_CODE)
        {
            var cATE_GBNParameter = cATE_GBN != null ?
                new ObjectParameter("CATE_GBN", cATE_GBN) :
                new ObjectParameter("CATE_GBN", typeof(string));
    
            var dEPTH1_CODEParameter = dEPTH1_CODE != null ?
                new ObjectParameter("DEPTH1_CODE", dEPTH1_CODE) :
                new ObjectParameter("DEPTH1_CODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADMIN_CATEGORY_TWO_SEL_Result>("SP_ADMIN_CATEGORY_TWO_SEL", cATE_GBNParameter, dEPTH1_CODEParameter);
        }
    
        public virtual int SP_ADMIN_CATEGORY_TWO_UPD(Nullable<int> iDX, string dEPTH2_NAME, string dISPLAY_YN, Nullable<int> rE_SORT, ObjectParameter iNTRESULT)
        {
            var iDXParameter = iDX.HasValue ?
                new ObjectParameter("IDX", iDX) :
                new ObjectParameter("IDX", typeof(int));
    
            var dEPTH2_NAMEParameter = dEPTH2_NAME != null ?
                new ObjectParameter("DEPTH2_NAME", dEPTH2_NAME) :
                new ObjectParameter("DEPTH2_NAME", typeof(string));
    
            var dISPLAY_YNParameter = dISPLAY_YN != null ?
                new ObjectParameter("DISPLAY_YN", dISPLAY_YN) :
                new ObjectParameter("DISPLAY_YN", typeof(string));
    
            var rE_SORTParameter = rE_SORT.HasValue ?
                new ObjectParameter("RE_SORT", rE_SORT) :
                new ObjectParameter("RE_SORT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ADMIN_CATEGORY_TWO_UPD", iDXParameter, dEPTH2_NAMEParameter, dISPLAY_YNParameter, rE_SORTParameter, iNTRESULT);
        }
    
        public virtual ObjectResult<SP_ADMIN_CATEGORY_VIEW_Result> SP_ADMIN_CATEGORY_VIEW(Nullable<int> iDX)
        {
            var iDXParameter = iDX.HasValue ?
                new ObjectParameter("IDX", iDX) :
                new ObjectParameter("IDX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADMIN_CATEGORY_VIEW_Result>("SP_ADMIN_CATEGORY_VIEW", iDXParameter);
        }
    
        public virtual int SP_ADMIN_CATEGORY_ONE_INS(string dEPTH1_NAME, ObjectParameter iNTRESULT)
        {
            var dEPTH1_NAMEParameter = dEPTH1_NAME != null ?
                new ObjectParameter("DEPTH1_NAME", dEPTH1_NAME) :
                new ObjectParameter("DEPTH1_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ADMIN_CATEGORY_ONE_INS", dEPTH1_NAMEParameter, iNTRESULT);
        }
    }
}
