//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboutMe.Domain.Entity.AdminProduct
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PRODUCT_INFO
    {
        public int IDX { get; set; }
        public string P_CATE_CODE { get; set; }
        public string C_CATE_CODE { get; set; }
        public string L_CATE_CODE { get; set; }
        public string P_CODE { get; set; }
        public string P_NAME { get; set; }
        public Nullable<int> P_COUNT { get; set; }
        public Nullable<int> SELLING_PRICE { get; set; }
        public Nullable<int> DISCOUNT_RATE { get; set; }
        public Nullable<int> DISCOUNT_PRICE { get; set; }
        public string SOLDOUT_YN { get; set; }
        public string P_INFO_DETAIL_WEB { get; set; }
        public string P_INFO_DETAIL_MOBILE { get; set; }
        public string MV_URL { get; set; }
        public string P_COMPONENT_INFO { get; set; }
        public string P_TAG { get; set; }
        public string MAIN_IMG { get; set; }
        public string OTHER_IMG1 { get; set; }
        public string OTHER_IMG2 { get; set; }
        public string OTHER_IMG3 { get; set; }
        public string OTHER_IMG4 { get; set; }
        public string OTHER_IMG5 { get; set; }
        public Nullable<int> RE_SORT { get; set; }
        public string DISPLAY_YN { get; set; }
        public string ICON_YN { get; set; }
        public Nullable<int> SELLING_COUNT { get; set; }
        public Nullable<int> P_VIEW_COUNT { get; set; }
        public string WITH_PRODUCT_LIST { get; set; }
        public string P_OUTLET_YN { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
    }
}
