//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboutMe.Domain.Entity.AdminDisplay
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AdminDisplayEntities : DbContext
    {
        public AdminDisplayEntities()
            : base("name=AdminDisplayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int SP_ADMIN_DISPLAY_REMOVE(Nullable<int> iDX)
        {
            var iDXParameter = iDX.HasValue ?
                new ObjectParameter("IDX", iDX) :
                new ObjectParameter("IDX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ADMIN_DISPLAY_REMOVE", iDXParameter);
        }
    
        public virtual int SP_ADMIN_DISPLAY_SAVE(Nullable<int> iDX, string kIND, string sUB_KIND, string uRL, string iMG, string p_CODE, string tITLE1, string tITLE2)
        {
            var iDXParameter = iDX.HasValue ?
                new ObjectParameter("IDX", iDX) :
                new ObjectParameter("IDX", typeof(int));
    
            var kINDParameter = kIND != null ?
                new ObjectParameter("KIND", kIND) :
                new ObjectParameter("KIND", typeof(string));
    
            var sUB_KINDParameter = sUB_KIND != null ?
                new ObjectParameter("SUB_KIND", sUB_KIND) :
                new ObjectParameter("SUB_KIND", typeof(string));
    
            var uRLParameter = uRL != null ?
                new ObjectParameter("URL", uRL) :
                new ObjectParameter("URL", typeof(string));
    
            var iMGParameter = iMG != null ?
                new ObjectParameter("IMG", iMG) :
                new ObjectParameter("IMG", typeof(string));
    
            var p_CODEParameter = p_CODE != null ?
                new ObjectParameter("P_CODE", p_CODE) :
                new ObjectParameter("P_CODE", typeof(string));
    
            var tITLE1Parameter = tITLE1 != null ?
                new ObjectParameter("TITLE1", tITLE1) :
                new ObjectParameter("TITLE1", typeof(string));
    
            var tITLE2Parameter = tITLE2 != null ?
                new ObjectParameter("TITLE2", tITLE2) :
                new ObjectParameter("TITLE2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ADMIN_DISPLAY_SAVE", iDXParameter, kINDParameter, sUB_KINDParameter, uRLParameter, iMGParameter, p_CODEParameter, tITLE1Parameter, tITLE2Parameter);
        }
    
        public virtual ObjectResult<SP_ADMIN_DISPLAY_SEL_Result> SP_ADMIN_DISPLAY_SEL(Nullable<int> iDX, string kIND, string sUB_KIND)
        {
            var iDXParameter = iDX.HasValue ?
                new ObjectParameter("IDX", iDX) :
                new ObjectParameter("IDX", typeof(int));
    
            var kINDParameter = kIND != null ?
                new ObjectParameter("KIND", kIND) :
                new ObjectParameter("KIND", typeof(string));
    
            var sUB_KINDParameter = sUB_KIND != null ?
                new ObjectParameter("SUB_KIND", sUB_KIND) :
                new ObjectParameter("SUB_KIND", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADMIN_DISPLAY_SEL_Result>("SP_ADMIN_DISPLAY_SEL", iDXParameter, kINDParameter, sUB_KINDParameter);
        }
    }
}
